### ISSUE TITLE
Dashboard concept using mock data

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#1]
Let's make an HTML dashboard that displays the output from some mock test runs.

Primarily, this iteration of the dashboard will be used to further the design discussion.

We know we will be running tests, and collecting data from the tests, and we'll want to make that data viewable somewhere.

We want to further discuss or design additional responsibilities of the dashboard, which might include:

* high-level overview of all the testing
* easy pinpointing of improvements or regressions in key metrics
* ability to view historical graphs of individual metrics
* ability to navigate to different code branches / pull-requests
* test plan scheduling management - accept commands to schedule certain test plans to run continuously, periodically, or on an ad-hoc (manual) basis
* infrastructure resource management - view and/or change cluster setups

@raulk proposed the following for the initial dashboard concept:

> A simple matrix like https://build.golang.org/ would work well for us, for now.
> • rows: reported result (e.g. time to first provider record, time to get file, time to find peer); grouped by test case (e.g. add and get 8mb file, find random peer, bitswap transfer no provider lookup, bitswap transfer with provider lookup).
> • columns: commits that have been tested. potentially with a second layer of nested columns inside each commit, one per test run — if we run each test plan several times in the canary setup, to account for variance
> • each cell contains the numeric value of the metric for that test run.
> • cell bg are traffic-light colour coded based on if the metric improved or worsened vs. a baseline.
> • we pick the baseline in a dropdown (master, commit X, release Y, etc.) 

I'd like to propose that we generate some realistic "mock" data for the first batch of tests that we would like to start running, and use that as a basis to rapidly prototype a design.

**Comment by jimpick** [comment]
I've got a repo where I've checked in some CSV files representing a minimal schema with three different tables:

* Git commits - synced from GitHub (probably via a webhook) ... one for each "sha" hash we'd like to test
* Metrics - names of numbers from tests we'd like to display on the dashboard
* Results - the actual data from the tests

Note, the final full schema will probably be a lot more complex. This is just something minimal so we can quickly iterate on it.

I've put the initial CSV files here. Additionally, I've used a "no-code" tool called [datasette](https://github.com/simonw/datasette) to turn them into a SQLite database with a UI and query interface so we can experiment with SQL queries:

https://github.com/jimpick/testlab-dashboard-mockup

**Comment by jimpick** [comment]
The current set of tests represented in the mock data are completely bogus. Instead, I'd like replace them with a more realistic set + a matching set of fake data points.

**Comment by jimpick** [comment]
Progress:

![Screenshot 2019-07-17 18 34 56](https://user-images.githubusercontent.com/20886/61422812-33576c80-a8c2-11e9-8230-26335f9f4edc.png)

Try it in your browser:

https://bafybeibwaofbcmruon6me3blchoqsik7idzyygjl4s3i3xbdxnln3umcpy.ipfs.dweb.link/

Mock data can be queried here: https://mockup-3knoa5s4ea-uc.a.run.app/mockup

This is just a base mockup for experimentation. I'm happy to try taking this mockup in any direction based on feedback.

**Comment by jimpick** [comment]
I made a Google Slides doc for comments (as requested by @raulk): 
https://docs.google.com/presentation/d/1NS8UoiGxilVuAXqHW1jfaTy6eZ6ZiTdTniqiWgFEiPQ/edit?usp=sharing

**Comment by Stebalien** [comment]
General metrics:
* Bandwidth used (in/out) by nodes participating in the test.
* Number of packets sent.
* CPU profile, memory profile, allocations profile, goroutine profile (probably linked or in some kind of hover-over tooltip)?
* CPU usage, memory usage, allocation count, goroutine count by subsystem/total.
* Time till $event.

Large Simulation: Everything above both for the nodes we're puppeting and the rest of the simulated network.

We may also want to average these and provide error bounds?

---

Bitswap Tests:

* 1 peer has the entire file.
* Many peers have the entire file with different latencies/bandwidth.
  * Primary metric: time (not new).
* Many peers have parts of the file.
  * Primary metric: duplicate blocks (or just bandwidth? we may not need anything new).

---

DHT Tests:

* Publish IPNS record.
* Find IPNS record.

Run these tests with:

* A freshly bootstrapped node.
* An unbootstrapped node.
* A node that has run N queries so far.

**Comment by raulk** [comment]
I'm gonna be moving this design to Figma because we need to iterate on it.

**Comment by raulk** [comment]
copying over my feedback from IM convo with @jimpick:

> (1) I think the direction the UI is taking is good. Thanks!
> (2) we need to find a way to illustrate min/avg/max, and potentially percentiles on hover, as we’ll be running the test plan N times for each commit. We don’t want to show the output from all iterations as that’s not efficient use of screen real estate. Each column could have a little plus button on the header which, when clicked, would expand that column like an accordion and show the specific results for each iteration. When folded, it would show min/avg/max values.
> (3) based on @Stebalien's input, each test case will use dedicated nodes (there will be no reuse across scenarios) — that’s how we can capture accurate network and system metrics _per test_. Same goes for profiles — they only make sense if the profiles contain data from a particular test case. If we mix test cases, they become useless because of the ambiguous context.
> (4) each test case will tag the node with name (e.g. in an add_then_get scenario, we will have an `adder` and a `getter`). the test runner will collect the general metrics (system and network stats, and profiles) and ship them to the coordinator via an API call.
