### ISSUE TITLE
TestGround Test Plans run on Cloud Infrastructure and its results are captured in a Dashboard

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#103]
Previous Trello Cards:

- https://trello.com/c/BclkJUod/55-tracking-card-aws-infra-phase-1
- https://trello.com/c/JVnpC5e8/33-aws-infra-phase-1-collect-container-outputs-into-elasticsearch-results-metrics-logs
- https://trello.com/c/9uvG4oTv/30-tracking-card-aws-infra-phase-2-multi-host-setup
- https://trello.com/c/qW3dT9ao/25-aws-infra-phase-1-deploy-a-static-redis-instance
- https://trello.com/c/qEzLZFmO/20-aws-infra-phase-1-deploy-docker-registry
- https://trello.com/c/P8bBVeWa/26-aws-infra-phase-2-docker-swarm-managers
- https://trello.com/c/2MJwZ71P/68-multi-machine-ssh-or-http-api-runner
- https://trello.com/c/8A6F2RBz/70-ecs-awsvpc-runner
- https://trello.com/c/qOnpp67k/11-evaluate-host-network-driver-vs-overlay-driver
- https://trello.com/c/0HZusDBT/12-simplify-to-docker-swarm-mode-for-launch
- https://trello.com/c/Bg4GqRON/57-evaluate-keydb-vs-redis

@jimpick you can now give us an update in this thread rather than a spread of trello cards :) You can still (and probably should) create multiple issues to review the technical details of each thread.

**Comment by jimpick** [comment]
Most of the work here will be landed in PR #111 when it is completed.

Notes:

- [x] https://trello.com/c/BclkJUod/55-tracking-card-aws-infra-phase-1

  - ElasticSearch is set up, Filebeat is configured via Ansible, and we deploy a Redis service on Docker Swarm

- [x] https://trello.com/c/JVnpC5e8/33-aws-infra-phase-1-collect-container-outputs-into-elasticsearch-results-metrics-logs

 - Data is sent to ElasticSearch / Kibana and it is possible to build reports/graphs with it

- [x] https://trello.com/c/9uvG4oTv/30-tracking-card-aws-infra-phase-2-multi-host-setup

  - We now use Ansible to write together a cluster with Filebeat, Docker Swarm, etc. 

- [x] https://trello.com/c/qW3dT9ao/25-aws-infra-phase-1-deploy-a-static-redis-instance

  - We deploy a Redis service on Docker Swarm

- [x] https://trello.com/c/qEzLZFmO/20-aws-infra-phase-1-deploy-docker-registry

  - The Docker builder now deploys to AWS ECR and the swarm runner fetches images from there https://github.com/ipfs/testground/pull/126

- [x] https://trello.com/c/P8bBVeWa/26-aws-infra-phase-2-docker-swarm-managers

 - The Docker builder now deploys to AWS ECR and the swarm runner fetches images from there https://github.com/ipfs/testground/pull/126

- [x] https://trello.com/c/2MJwZ71P/68-multi-machine-ssh-or-http-api-runner

 - This was suggested as a quick way to get running without using docker swarm, but now that docker swarm is implemented, I don't think we need to do it now.

- [ ] https://trello.com/c/8A6F2RBz/70-ecs-awsvpc-runner

 - This is a potential area to explore for advanced networking setups that use AWS VPC infrastructure directly. It should be possible to use the awsvpc Docker networking driver outside of ECS. It doesn't sound like we need it immediately, but it's just another option for doing interesting networking things using Amazon's infrastructure.

- [x] https://trello.com/c/qOnpp67k/11-evaluate-host-network-driver-vs-overlay-driver

 - We're using overlay networks with Docker swarm.

- [x] https://trello.com/c/0HZusDBT/12-simplify-to-docker-swarm-mode-for-launch

 - We now have a Docker Swarm runner implemented.

- [ ] https://trello.com/c/Bg4GqRON/57-evaluate-keydb-vs-redis

 - We are currently using plain Redis, but may switch to KeyDB. @raulk is evaluating.

**Comment by raulk** [comment]
I _think_ this is complete. The remaining KeyDB task is something to discuss/track in a separate issue.

**Comment by daviddias** [comment]
@raulk this issue tracks the whole KR `TestGround Test Plans run on Cloud Infrastructure and its results are captured in a Dashboard` of Q4 OKRs. It is just a hub to upgrade on progress.

**Comment by daviddias** [comment]
Got a recommendation from Why to check out OpenTracing combined with Jaeger (https://www.jaegertracing.io/) as a great solution to visualize what happened on a run.

-

**Comment by jimpick** [comment]
I had that all set up for peer-base testing (OpenCensus + Jaeger). Theoretically, I could run those tests on testground with just a few small modifications.
