### ISSUE TITLE
Incorporate notes from 2019-10-22 sync into documentation

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#106]
- https://github.com/ipfs/testground/pull/78#discussion_r337809993
- https://github.com/ipfs/testground/pull/78#discussion_r337781791

**Comment by daviddias** [comment]
@jimpick is this still required or now is it out of date?

**Comment by raulk** [comment]
This seems stale; closing. I [made an issue for adding sync SDK examples](https://github.com/ipfs/testground/issues/354), inspired by @jimpick's braindump on https://github.com/ipfs/testground/pull/78#discussion_r337809993.
