### ISSUE TITLE
[WIP] Preliminary cluster:swarm runner

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#110]
Work-in-progress...

I have an automated Ansible setup for Docker swarm in the aws-ansible branch (needs just a bit more cleanup). I first tested it with a shell script, but then I realized that it wouldn't be too much work to modify the local:docker runner to talk to the swarm API.

Here's a demo running the smlbench2 2-container bitswap test across 2 different EC2 vms in the Docker swarm cluster:

![tg-docker-swarm-runner](https://user-images.githubusercontent.com/20886/68005983-553beb80-fc34-11e9-801c-eaa0f046033e.gif)

https://github.com/ipfs/testground/blob/aws-ansible/pkg/runner/cluster_swarm.go

It's not quite done yet ... I've hard-coded the image (pulling from ECR), the REDIS_HOST environment variable, and the network. We'll want to upload the image to ECR after building it before creating the service.

**Comment by daviddias** [comment]
PR with WIP at https://github.com/ipfs/testground/pull/112 Continue the conversation there.
