### ISSUE TITLE
github integration: lay the foundation

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#12]
## What we need to do

Write a `GitHubBridge` component that:
  * sets up a webhook endpoint.
  * subscribes to commits on master, commits on pull requests, and comments on PRs.
  * prints out those events to stdout.

Can be tested manually against a personal repo (don't create test PRs or commits on go-ipfs itself!). Not sure how this can be unit tested; maybe create integration tests that use a personal repo and the GitHub API to make commits, etc. that trigger the events we'll receive via the webhook endpoint. You can register and remove webhooks dynamically via the WebHook API: https://developer.github.com/v3/repos/hooks/. 

This integration test will also need to run on Travis (we need to set up Travis -- can do that in this issue too?).

## Definition of Done

- [ ] Documented code.
- [ ] Integration tests against a personal repo, using the webhook API to dynamically register a webhook, and the general GitHub API to make actions that lead to webhook notifications.
- [ ] Pull request.
- [ ] Travis config.

**Comment by jimpick** [comment]
Why not just subscribe to everything manually? Less likely to fail, less to test.

![Screenshot 2019-07-19 06 51 56](https://user-images.githubusercontent.com/20886/61540265-26399b00-a9f2-11e9-8595-3501abd79241.png)

**Comment by raulk** [comment]
That works @jimpick.

**Comment by jimpick** [comment]
I'm going to wrap this up on Monday...

https://github.com/jimpick/go-canary-testing-github-bridge

(just need to figure out how to test it using mock http requests with the test data I saved)

I built a bit of an abstraction as an exercise, but it's not clear to me whether or not it's a win over just using the raw go-github module, which already makes things super easy.

**Comment by jimpick** [comment]
I'm not actively working on this, so I removed myself from the issue.

**Comment by raulk** [comment]
This will be worked on during Maturity Stage 2 (TaaS -- Testground as a service). Refer to #643 for more info. We will reopen/redesign this solution when the time comes. Closing it to clean up the backlog, in order to keep it relevant.
