### ISSUE TITLE
Make logs be friendly to JSON tools

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#128]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1211152/68330963-08d92b80-00cc-11ea-9d84-acf070440cc8.png">

**Comment by raulk** [comment]
This is the CLI tool being user-friendly and adding the colourful prefix for visuals. JSON tools should read directly from the docker logs, which only contain ndjson logs.

**Comment by raulk** [comment]
Since we refactored test outputs, all standardised logs are ndjson.

**Comment by raulk** [comment]
Output is all JSON now, emitted via zap.

**Comment by Robmat05** [comment]
Old ticket, should not be associated with any new milestone
