### ISSUE TITLE
Design Session: TestGround Dashboard - Intelligence Visualization

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#133]
It would be good to do a quick planning/design session to get on the same page about what we are going to do with the output from testground.

We can currently get the data into filebeat (using a ad-hoc JSON based structure). We'll need to figure out what schema works for generating graphs in Kibana and how to tag / organize things for multiple tests.

It would also be good to draw on paper some people's ideas of what a simple dashboard and test report page might look like for our first iteration.

**Comment by jimpick** [comment]
30 minutes

Questions:

* what does the dashboard look like?
* what does a test report look like?
* do we want multiple users to see a common dashboard with multiple tests?
* do we want to be able to see the active cluster state / job queue?
* do we want to be able to manipulate the cluster state?

**Comment by raulk** [comment]
I'm more interested in getting the Kibana pipeline working in the first place.

There are some technical issues we need to solve, such as containers being deleted before their logs are harvested.

We will be better poised to answer the questions @jimpick outlines once we see the data flowing in in our test cluster, and we play around with it. I haven't seen it working end-to-end yet, so we gotta debug that first.

Re: dashboards, I think they will be dependent on the test plans / test cases. At this stage, I'm more interested in the exploratory capabilities of Kibana than on building static dashboards.

> do we want to be able to see the active cluster state / job queue?

This will be hard to visualise in Kibana, unless we can consume an event stream from the docker swarm manager. In a custom-made dashboard (like the one we had set out to build initially), we can pull in this data from the docker swarm manager.

> do we want to be able to manipulate the cluster state?

I would make this a P2. In an eventual custom-made dashboard, yes, but I'm more interested in querying the state and the metrics, than managing the cluster (as we already have other tools for that).

> It would also be good to draw on paper some people's ideas of what a simple dashboard and test report page might look like for our first iteration.

I do want to stress that we did some conceptualisation at the beginning of the project. Can you post the URL to the dashboard mockup you created, @jimpick, to use that as a basis?

**Comment by jimpick** [comment]
https://ipfs.io/ipfs/QmZRPBvtkDcbvZxm2sPHcAgKaf5ugc3ez3LhMTv2EeZEnb/

The source for the dashboard mockup is here:

https://github.com/jimpick/testlab-dashboard-mockup

(The dashboard html is in the "static" directory)

**Comment by raulk** [comment]
Here's an rough mockup of where my thinking currently is: https://app.moqups.com/me0tpXE4aA/edit/page/aa9df7b72

**Comment by olizilla** [comment]
i'd note that tailwind css is a flavour of the same idea as [tachyons](https://tachyons.io/) css... _many composable, single purpose css classes._ We also have https://github.com/ipfs-shipyard/ipfs-css which would pair nicely with either

**Comment by daviddias** [comment]
I've been capturing our notes into a [PRD (Product Requirements Document) here](https://docs.google.com/document/d/1oc82MDphSdZXWJAfWpfYWo396p0LZyThgRcPzYtx9Pk/edit)

**Comment by daviddias** [comment]
Just got out of a conversation with @olizilla on TestGround Dasboard. It was a useful conversation and a good check in to what our timelines could look like. I'll take on putting some thinking into writing on the TestGround Dashboard endeavor next week.

**Comment by raulk** [comment]
Discussion and sketches will be picked up in Maturity Stage 2 (TaaS -- Testground as a service). Refer to #643 for more info.
