### ISSUE TITLE
Automate EC2 provisioning with Terraform or CloudFormation

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#134]
Setting up a new cluster in the AWS Web Console using autoscaling groups is currently fairly easy, but we'd like to have it automated so we can consistently tag resources, etc.

Also, if we decide to experiment with more exotic network setups using Amazon VPC, we'll want some automation.

Two options:

* https://www.terraform.io/ - cross-platform, runs from a CLI (eg. on a laptop or in a VM somewhere)
* https://aws.amazon.com/cloudformation/ - AWS specific, API call

Most of the automation is already done using Ansible and we have a base image built with Hashicorp Packer, so the recipe is quite simple. We could even do both.

I have a lot of experience with CloudFormation, which is a tricky system to develop against, but has good support direct from AWS. Terraform is a bit friendlier ... our needs are currently pretty simple.

**Comment by daviddias** [comment]
Done with https://github.com/ipfs/testground/pull/111
