### ISSUE TITLE
Base infrastructure benchmarking for capacity planning

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#135]
There are a wide variety of EC2 instance types with different combinations of CPU, memory, disk (EBS, SSD, etc.), network etc.

https://aws.amazon.com/ec2/instance-types/

Pricing varies based on a lot of different factors as well:

https://aws.amazon.com/ec2/pricing/

Specific test cases will have different performance depending on what hardware they are run on. It would be a good work package to try them out on different instance types and compare the results so that we can make informed decisions about which ones to choose.

**Comment by dirkmc** [comment]
@hinshun I believe we had issues when trying to benchmark Bitswap with smaller instance types, is that correct?

**Comment by hinshun** [comment]
Yes, `bitswap` seems to be more bound by number of CPUs than network bandwidth. We were most successful with 8+ CPUs and 1+ Gbps.

@jimpick This may be useful to you: https://www.ec2instances.info/

**Comment by jimpick** [comment]
I'm going to close this for now... I think we may want to revisit this once we have more tests in production.
