### ISSUE TITLE
Impl Plan - Interop (Import ipfs/interop tests to Testground)

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#138]
With #137, import all tests written in https://github.com/ipfs/interop to Test Ground, hence creating the _Interop Test Plan_

**Comment by daviddias** [comment]
Hi there! I'm checking in to learn about the progress on the writing of this Test Plan. AFAIK (from what you told me) there is some really awesome progress with the testing using the WASM compiler. Could you drop here a status update with a list of next steps on your mind?

**Comment by achingbrain** [comment]
I've not had a whole bunch of time to work on this, sorry.  Where I'm at:

1. Compiled project to WASM
1. Round tripping from js -> go -> js
1. Added wrappers around exported go functions to allow go panics to translate to js errors
1. Started porting one of the existing testground dht tests to js to prove that we can use the same sdk

Next steps are:

1. Finish the test
1. Make it demoable
1. Submit a PR that builds a js version of the SDK, or perhaps publish a parallel module that wraps up the WASM and other niceties into something more easily consumed (we should discuss what we want out of this first)

**Comment by raulk** [comment]
I think migrating the tests as-is will provide little value. What I'd like to see is `exec:js` and `docker:js` builders that can build an interop test plan written in JS (targeting js-ipfs) into executables and docker images so they can be composed via a composition with an analogous Go test plan (targeting go-ipfs). 

This is how we'd form the interoperability test scenario.

Also, this has been inactive for a while, so I'm closing it and tagging it as rotten. We can rescue it from that bucket going forward.

**Comment by raulk** [comment]
@achingbrain would you like to post the WIP you had to a branch?
