### ISSUE TITLE
Set HOSTNAME in local_exec runner

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#144]
The sidecar needs every instance to have a new hostname.

**Comment by raulk** [comment]
@Stebalien is sidecar designed/intended to work with `local:exec` (now or eventually)? Trying to figure out the urgency of this issue.

**Comment by Stebalien** [comment]
Eventually, but we can probably close this for now given that we've punted on that.

**Comment by Stebalien** [comment]
(i.e., the real issue is: make the sidecar work locally)
