### ISSUE TITLE
Delegate testground.ipfs.team DNS to Route 53

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#145]
If we do this, then we can dynamically create DNS entries within the AWS platform for various assets.

**Comment by daviddias** [comment]
@olizilla can we haz this?

**Comment by nonsense** [comment]
@olizilla I created a Hosted Zone in our AWS account, so that we can manage this within our team - https://github.com/ipfs/testground/pull/208. Let me know if that makes sense.

If yes, I could send you the NS endpoints off-band so that you can update the domain records.

Thank you!

**Comment by olizilla** [comment]
@nonsense good plan! go for it.

**Comment by nonsense** [comment]
`testground.ipfs.team` NS records updated by @olizilla . Thanks a lot!
