### ISSUE TITLE
Dependency graph tracking

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#147]
When we produce a build, we want to capture the entire dependency graph in effect and store it in the state database. This will enable us to:

* search for runs that tested `go-libp2p-kad-dht` commit `7aa5b0ef` (for example). 
* easily generate performance charts where module `X` was in the runtime across all revisions of module `X`, contextualised to a specific plan `A`.
* dashboard UI: find a build to set as a comparative baseline.

**Capturing this data is responsibility of the builder.**

The implementation language of a test plan (e.g. Go, Javascript, etc.) will have its own tooling to calculate a dependency graph. For Go, we can use `go mod graph`.

In builder `exec:go`, this is as easy as running `go list -m all` as an `exec.Command()` and processing the output.

In builder `docker:go`, my suggestion is to add a `RUN` in the `Dockerfile` that dumps the dependency graph in a demarcated block so the builder can slice this output and process it as per above:

```
RUN echo "-----BEGIN GO MOD LIST-----" && go list -m all && echo "-----END GO MOD LIST-----"
```

The dependency graph needs to be sent off to the run state database, which will be specified in another issue.

**Comment by hacdias** [comment]
Leaving here a documentational note: I asked @raulk if we needed to do #148 before or if we could just implement this through `BuildOutput`. I was told the latter is the way to go!
