### ISSUE TITLE
Testground Daemon Implementation (does not include Github Integration)

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#149]
Features like tracking the run state (https://github.com/ipfs/testground/issues/148) and dependency graph tracking (https://github.com/ipfs/testground/issues/147) start making sense in an environment where testground runs as a daemon, and developers interact with the testground by sending commands to that daemon.

After all, we don't want to track local test runs in a shared database. We only want to track cluster runs whose outputs are available in Elasticsearch/Kibana/the future dashboard.

<details><summary>ORIGINAL TASK OUTLINE (outdated)</summary>
<p>

This issue outlines the potential requirements of a _minimal daemon_ -- they're up for discussion:
- [ ] New binary `daemon`.
- [ ] Exposes a JSON-RPC endpoint to receive run requests. In the future, it'll expose more operations.
- [ ] New `remote-run` command in the `testground` executable. It is equivalent to `run` but only supports remote runners, e.g. cluster:swarm (we need to decorate such runners with a trait like `remotable` to mark them). Sends a JSON-RPC request to the daemon endpoint.
- [ ] New `[remote]` block in the `.env.toml` file. For now, with a single property `endpoint` that is the (tunnelled) URL of the daemon JSON-RPC endpoint.
- [ ] No authentication. For now we can assume that everyone that's authorised has an ssh tunnel to the daemon.
- [ ] JSON-RPC command: `update-daemon`. This project moves fast, and we need to automate the way that we update the daemon to the latest master commit. This command pulls from origin/master on the source working copy, rebuilds the daemon (`go install .`), and exits with a 0 code. `systemd` should take care of restarting the daemon with the new version.

</p>
</details>

**Refer to this comment instead: https://github.com/ipfs/testground/issues/149#issuecomment-555651769**

For now, this is a _passive_ daemon. It does not integrate with GitHub.

**Comment by hinshun** [comment]
I implemented a small package to build a go package of an arbitrary `ref/commit/branch` of a git repository for `p2plab` here: https://github.com/Netflix/p2plab/blob/master/builder/builder.go#L153

I think the parts interesting to you guys may be the git shallow cloning voodoo magic.

**Comment by nonsense** [comment]
```
JSON-RPC command: update-daemon. This project moves fast, and we need to automate the way that we update the daemon to the latest master commit. This command pulls from origin/master on the source working copy, rebuilds the daemon (go install .), and exits with a 0 code. systemd should take care of restarting the daemon with the new version.
```

Do we really want this logic in the testground binary? This assumes that the machine where we run testground actually has go installed with the proper version, and all the tools used to build the project. I am not sure what the value of pushing this logic to testground is - why not just run the build/deploy playbooks when you want to update a given testground service, rather than issuing a JSON RPC request? Of course, this could be automated.

I am probably missing some of the background for this.

**Comment by raulk** [comment]
Pasting the conversation for public reference:

> @raulk:
> We can go either way, I don’t have strong opinions. What’s important is that it’s dead simple to update a remote daemon. In fact, we can deploy the daemon inside the docker swarm and just push an image + docker service update. That way we don’t even need an Ansible script.
>
> The way we’d do this is placing the daemon service on the machine labelled with “master”, and having it use host networking. That’s to avoid the ingress endpoint magic
>
> @nonsense:
> @raulk yes, something like that. I am not very familiar with docker swarm , but this is what I had in mind - build and deploy are separate steps, and I just don’t see the value of having them in the binary itself. Especially if the build process gets more complicated in the future.
> 1. Ultimately we want a build and image push to a registry.
> 2. Pull and restart of the service wherever it is running
>
> @raulk:
> Sometimes it’s useful to build transitory functionality that’s marked exactly as that, if it’s going to speed up your development
>
> @nonsense:
> OK, makes sense.

**Comment by raulk** [comment]
@nonsense and I caught up in person to iterate on this design. We've decided to simplify things. This is the prevalent design now:

* introduce new `testground daemon` command. This runs a testground daemon.
* all existing `testground` commands become thin client commands, i.e. all they do is send a request off to the daemon. If the user is running testground locally, they would start a local daemon.
  * this architecture is similar to IPFS, docker and kubectl, where the CLI is just a client.
* a `[daemon]` block in the .env.toml file would define the listen endpoint URL, and details like whether state recording is enabled, the backend type (elasticsearch?), the backend URL, etc.
* a `[client]` block in the .env.toml file would define the remote endpoint for the thin commands.
* think about the protocol between the client and the server. JSON-RPC doesn't allow for streaming output. Possible options: WebSockets with a simple enveloping protocol for stdout, stderr and results; or gRPC with streams.
* future: we need a build queue.

**Comment by raulk** [comment]
This was implemented long ago; closing down ;-)
