### ISSUE TITLE
AWS Docker Swarm workload rearrangement

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#152]
I'd like to request the following changes on the way that we configure our cluster and and schedule workloads in Docker Swarm.

- [x] *Place redis in a dedicated docker node.* Rationale: (1) it is the most contended resource in the system, (2) if we migrate to KeyDB, it expects exclusive usage of the cores assigned to it, (3) it is memory-only, so optimise for fast memory and bandwidth. 
- [x] Assign a labels to nodes:
    * `redis` label to the above node.
    * `master` label to the docker swarm master.
    * `worker` label to all other nodes.
- [x] Make the `cluster:swarm` runner schedule workloads only on `worker` nodes, by adding a placement constraint to the service spec.
- [x] Redis EC2 machine type: `c5.large`.
- [x] Docker Swarm EC2 machine type: `c5.large`.
- [x] Worker machine type: `m5.xlarge` in an auto-scaling group that keeps minimum 2 up, maximum 4 for now.

**Comment by jimpick** [comment]
Pretty easy to set up using Terraform. I'll drop the changes in.

**Comment by jimpick** [comment]
s/master/manager/

**Comment by jimpick** [comment]
Everything is implemented in https://github.com/ipfs/testground/pull/111 except for the `cluster:swarm` runner changes.

**Comment by raulk** [comment]
@jimpick can you file a PR for...

>  Make the cluster:swarm runner schedule workloads only on worker nodes, by adding a placement constraint to the service spec.

?

**Comment by jimpick** [comment]
@raulk I added the constraint in PR #177

**Comment by jimpick** [comment]
Everything is checked off, so I'm closing this.
