### ISSUE TITLE
Finding Redis on Windows

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/testground#158]
The functionality for automatically finding the Redis host on Windows 10 is anti-helpful.

https://github.com/ipfs/testground/blob/ebdb2f646b6064e7505e5c065209aa9a3d65d830/sdk/sync/common.go#L38-L49

Redis installation: I followed the recommended way to install redis on Windows 10 https://redislabs.com/blog/redis-on-windows-10/, which is just a simple apt install within WSL.

When running the example test using the default detection mechanism results in `panic: dial tcp 192.168.X.Y:6379: connectex: No connection could be made because the target machine actively refused it.`

However, if I set the environment variable `REDIS_HOST=localhost` then it works. Maybe if the connection tries out we should try localhost, or we could figure out why the detection mechanism is failing.

**Comment by raulk** [comment]
"actively refused it" 😄 That's an intense way of describing it.

In theory this logic is designed to fall back to `localhost` (that's how I designed it and I thought I implemented it), but maybe the `LookupHost` is giving us a false positive here? Could you debug if that's the case?

**Comment by aschmahmann** [comment]
Yes the `LookupHost` does returns `192.168.X.Y` for `host.docker.internal`

**Comment by daviddias** [comment]
@hacdias didn't you get this fixed?

**Comment by hacdias** [comment]
I don't think so, but I can take a look!

**Comment by hacdias** [comment]
After talking to @nonsense, we agreed that this is more of a problem with the configuration on the machine and not an issue with Testground itself. Right now, we're trying to guess where is Redis being run, but I don't believe that just because it fails this should be a bug. It should be the user's responsibility to set the required environment variables if it's failing.

It seems to me that Redis is refusing the connection on hosts other than `localhost` by default on Windows, in opposition to what's happening on other platforms. So I'd think that this is more of a Redis issue than Testground's.

What do you all think?

**Comment by daviddias** [comment]
To avoid having more users confused in the future, can you print a log that suggests the Windows users to configure redis to support localhost?

**Comment by hacdias** [comment]
Looking at the code again, I don't think we should print a message specifically to Windows users. The code currently does the following:

- Sets host as `localhost`
- Tries to resolve `testground-redis`. If it does, replaces host
- Tries to resolve `host.docker.internal`. If it does, replaces host

I searched online and `host.docker.internal` seems be this:

> The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name host.docker.internal, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Windows.
> [Source](https://docs.docker.com/docker-for-windows/networking/)

In this case, `host.docker.internal` can be resolved, but there is no service listening at that ip:port combo. I think the error is already self-explanatory. It's a connection refused, hence something is wrong with the user's configuration and it might happen on Windows, macOS or any other OS.

I don't even understand why we're trying to connect to the "outside" world outside of Docker. This should only be happening inside Docker. @aschmahmann, is it running inside Docker? If not, it shouldn't even be resolving that hostname...

IMO, we should just remove guessing, but keeping the defaults to localhost. Any other address should be set explicitly. I'm pretty sure @raulk has more info about what might be happening here than I do.

**Comment by aschmahmann** [comment]
@hacdias it's been a while since I looked at this and testground has changed in the meanwhile. When running through the [USAGE.md]( https://github.com/ipfs/testground/blob/9c0992c091dbd4fc2e876a9f4938cae1c8d56a00/docs/USAGE.md) I didn't run into any issues that weren't explained by Redis.

**Comment by hacdias** [comment]
@aschmahmann sorry if I didn't understand correctly: everything is working now?

**Comment by daviddias** [comment]
Seems like it! :) Closing, reopen if necessary.
