### ISSUE TITLE
Re-create broken containers

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#173]
When we fail to start redis, the sidecar, etc. We should remove and recreate them.

**Comment by jimpick** [comment]
Just need to be careful that we don't end up in a loop...

**Comment by raulk** [comment]
This logic would go in the runner init method: https://github.com/ipfs/testground/issues/339

**Comment by raulk** [comment]
This logic now goes in the Healthcheck repair=true pathway.

**Comment by raulk** [comment]
Recreating broken containers for `local:docker` was implemented in #557. Kubernetes support coming in #623, and tracked in #625; closing this one down.
