### ISSUE TITLE
Infra: EC2 Placement Groups

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#178]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html

We could use a "Cluster" placement group – "packs instances close together inside an Availability Zone. This strategy enables workloads to achieve the low-latency network performance necessary for tightly-coupled node-to-node communication that is typical of HPC applications."

There is support in Terraform:

https://www.terraform.io/docs/providers/aws/r/placement_group.html

**Comment by daviddias** [comment]
@nonsense is this issue still relevant today?

**Comment by nonsense** [comment]
This seems like a nice-to-have optimisation, rather than a problem we have right now. I'd keep it around as an idea, but not spend energy on it right now.

**Comment by jimpick** [comment]
Potentially it could be a major performance optimization when it comes to networking. I know @raulk put some effort into selecting the right instance types so we can have high networking performance, so I think we care about that.

I've never used them and I don't have a workload ready to benchmark them, so I can't say what the impact would be. It seems pretty simple to add them to Terraform.

**Comment by raulk** [comment]
Let's cross this bridge if we come to a point where the effect that AWS intra-AZ network latencies are having on the outcomes of our tests is both (a) measurable and (b) provenly detrimental. Moving to future.
