### ISSUE TITLE
plan DHT - Do not dial to all nodes on warm up (prev "Stop dialing everyone")

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#184]
The DHT setup logic currently fully connects all nodes. This defeats the whole point of a DHT.

**Comment by momack2** [comment]
I'd like a full checklist for the expected DHT changes that links to this and other specific bugs. Can we get a meta tracking issue with the full set that is prioritized and sized so we can distribute ownership?

**Comment by raulk** [comment]
We don't dial everyone any longer.
