### ISSUE TITLE
Infra: Add ssh keys for team members automatically

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#186]
Previously discussed here: 

* https://github.com/ipfs/testground/pull/111#issuecomment-551974819
* https://github.com/ipfs/testground/pull/111#issuecomment-552525795

Fetch teams from:

* https://github.com/orgs/ipfs/teams/testground/members
* https://github.com/orgs/ipfs/teams/wg-go-core/members
* https://github.com/orgs/ipfs/teams/wg-js-core/members

I think I'd like to configure this via a file in an S3 bucket on our account so that we don't hard-code the team names into the source, so outside users of testground aren't accidentally surprised by granting ssh access to accounts they weren't expecting.

**Comment by jimpick** [comment]
PR #185 automatically copies keys from an authorized_keys file placed on a webserver on the manager node. So an easy implementation would be to just add the extra keys to that file.

**Comment by raulk** [comment]
Done in https://github.com/ipfs/testground/pull/551.
