### ISSUE TITLE
Using TestGround with CI

### ISSUE THREAD

**Issue by dirkmc** [ipfs/testground#189]
> We would like to use TestGround as part of the CI process to decide if for example a PR can be merged

As an example, each time a PR is created against [go-bitswap](https://github.com/ipfs/go-bitswap), it runs [benchmarks](https://github.com/ipfs/go-bitswap/blob/master/benchmarks_test.go) and compares them to master to decide if the PR should be accepted (see [example benchmarks run](https://circleci.com/gh/ipfs/go-bitswap/355)).

Generalizing to TestGround, it should be possible to
- Run tests with different parameters
  eg number of seeds / leeches
- Collect artifacts from the tests
  eg logs
- Parse artifacts to produce data points
  eg number of duplicate blocks, time to fetch data
- Compare data points from this run (eg against a PR branch) to a previous run (eg against master)
  eg is number of duplicate blocks more than 10% higher than previously
- Output a boolean accept / reject for CI

**Comment by daviddias** [comment]
Relevant for #11

**Comment by raulk** [comment]
Thanks a lot for recording this idea. I'm grooming the backlog to make sure that relevant, sufficiently-specified, actionable work remains. Tagging with `status/deferred`.

**Comment by raulk** [comment]
FTR, the individual features requested in the bullet list have been implemented; we just haven't automated the process of running CI pipelines yet. That's coming in TaaS (Testground as a Service); maturity stage 2, as per our roadmap #643.
