### ISSUE TITLE
Some runners are incompatible with some builders and fail silently

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#191]
Trying to run TestGround with:

```
testground -vv run dht/find-peers --builder=exec:go --runner=local:docker --test-param timeout_secs=15
```

results in silent failure, probably because we cannot run a test plan in docker, while asking to run a build with `exec:go`.

**Comment by Stebalien** [comment]
See https://github.com/ipfs/testground/pull/181/checks?check_run_id=316818147

**Comment by raulk** [comment]
I had modelled for this by adding a `CompatibleBuilders()` accessor to the `Runner` interface. It's possible that it's not getting used.

**Comment by hacdias** [comment]
@raulk I see you did, but they're not being checked anywhere. Will check that out
