### ISSUE TITLE
Pass Arrays and Objects to Test Parameters

### ISSUE THREAD

**Issue by hacdias** [ipfs/testground#195]
I'm now taking a look at #58 ("Chewing Large Datasets" Plan) and I want to make it better! @daviddias set some ideas for the [test parameters](https://github.com/ipfs/testground/tree/test-plan-1/plans/chew-large-datasets#test-ipfs-add-defaults):

> - `File Sizes` - An array of File Sizes to be tested (default to: [1MB, 1GB, 10GB, 100GB, 1TB])
> - `Directory Depth` - An Array containing objects that describe how deep/nested a directory goes and the size of files that can be found throughout (default to [{depth: 10, size: 1MB}, {depth: 100, size: 1MB}]

As far as I understood right now, we're passing the parameters with the flag `--test-param key=value`, right? If so, how will we pass arrays and other types of variables. I can work on that, I just to come to an agreement on how to do it 😃 

## Way 1

We could pass arrays like this:

```
--test-param arrKey=value1 \
--test-param arrKey=value2 \
--test-param arrKey=value3
```

It's easy to parse and we can easily define arrays. However, this wouldn't solve how to pass custom objects.

## Way 2

Just pass a JSON-like object:

```
--test-param array=[1MB, 1GB, 10GB, 100GB, 1TB]
```

Then, we could call `runenv.StringArrayParam` or `runenv.StringSliceParam`. The same for other basic data types that we already have right now. This would work for slices.

We could also add a `runenv.JsonParam` that would unmarshal to a specified data type (taken as an argument). This would work for slices and objs.

## Way 3

Just implement `runenv.JsonParam` from Way 2.

/cc @daviddias @raulk

**Comment by daviddias** [comment]
@hacdias is there a way 4 that would not require specifying the type. Example: `--test-param=["1MB", "1GB", "10GB", "100GB", "1TB"]`

**Comment by hacdias** [comment]
@daviddias how so? When I wrote `array`, I meant `keyName`, it was not the type. For example:

```
--test-param keyForAnArray=value1 \
--test-param keyForAnArray=value2 \
--test-param keyForAnArray=value3
```

Sorry for calling it array. It certainly can be confusing

**Comment by daviddias** [comment]
I like way 2 then :)
