### ISSUE TITLE
Fake bitswap + datastore for mixed testing

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#21]
I would be neat to do a "fake bitswap + datastore" thing we could slap into an IPFS test build that would pretend it was transferring over the network at a simulated rate, but wouldn't actually transfer blocks ... it would use a out-of-band backchannel to communicate any hashes that the other end needed.

We could do mixed simulation, but with many lightweight (but real) nodes on a real network for things like package manager use cases with massive numbers of clients.

It's pretty inexpensive to spin up lots of nodes in the cloud using a serverless platform such as Cloud Run (or maybe AWS Fargate), but if we want to send lots of real traffic across multiple regions, that costs $$$.

**Comment by raulk** [comment]
I’d go a bit further and say we probably don’t ever want to run cross-region tests. Spreading a deployment across regions is a tool for availability and redundancy of long-running services. Our tests are really ephemeral jobs. We should be simulating latencies, jitter, packet loss, bandwidth with a tc-based API that operates on Docker network adaptors.

**Comment by raulk** [comment]
However I do see this tool being useful for other purposes, such as when you want to behaviourally remove Bitswap out of the picture. I’d envision this as a shared directory mounted to the many Docker containers that participate in a test. Bitswap would wrap around that directory and keep track via symlinks of which nodes hold which CIDs. A Bitswap transfer would just be a new symlink created synchronously.

**Comment by daviddias** [comment]
> I’d go a bit further and say we probably don’t ever want to run cross-region tests. 

This is a great idea and something I hadn't considered when I got to the writting of #33. Adding a note there.

**Comment by daviddias** [comment]
This will be a feature of a Plan design more than Testground itself. Closing for now, will reopen later if necessary
