### ISSUE TITLE
Write a design blueprint for the daemon architecture

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#212]
Take https://github.com/ipfs/testground/issues/149 + design decisions taken during implementation of #183, and lock them in a design blueprint doc under `/docs`.

**Comment by nonsense** [comment]
I like the idea of writing design docs for various parts of the architecture of Testground. We could later render them similarly to how the Perkeep docs are rendered at https://perkeep.org/doc/ (source at: https://github.com/perkeep/perkeep/tree/master/doc)
