### ISSUE TITLE
Large Datasets Plan & External Daemon

### ISSUE THREAD

**Issue by hacdias** [ipfs/testground#215]
Related to #93.

Some functions or commands are not available through the API so we'll need to make this work with the daemon. I'm not fully aware of the possibilities on how to run the daemon here.

I am thinking of running `ipfs daemon` and then executing all the other commands through Go's `exec` library. Is that feasible? Is there a better way you're thinking of doing this?

Also, if we go this way, how can we bundle/build `go-ipfs` binary on the test if we're just building one binary? If we're going to run the commands externally, we'll need the binary.

Is there any other way of doing this I'm not aware of? Like embedding the daemon and running the commands programmatically?

/cc @daviddias

**Comment by daviddias** [comment]
> (I’m on the go so my response will be brief)

@hacdias check the smlbench Plan for an example on how to use IPTB to spawn an ipfs-daemon

**Comment by hacdias** [comment]
@daviddias thank you very much! I think I already figured it out! I will start implementing the tests we already have with the IPTB too and gain some experience. Then, I will move to the other tests.

**Comment by hacdias** [comment]
Just one more note: IPTB uses `go-ipfs-api` which does not also implement any `Files`/`FileStore`/`UrlStore` APIs. Those will also need to be implemented.

**Comment by daviddias** [comment]
@hacdias, I can't wait to see you powering through these hurdles and add all sorts of new goodness to the go-ipfs ecosystems of packages! ❤️

**Comment by daviddias** [comment]
@hacdias I believe we can declared this one as answered. Closing (reopen if necessary)
