### ISSUE TITLE
Create instructions on how to use Sidecar

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#221]
From https://github.com/ipfs/testground/pull/172

> - [ ] Also add to https://github.com/ipfs/testground/blob/master/docs/USAGE.md an example on how to use Sidecar

**Comment by jimpick** [comment]
Sidecar usage is a bit more advanced ... it would be nice to keep USAGE.md really simple so people can get started quickly.

It might be nice to have separate documentation for advanced test plan writing that gives a tour of the SDK, etc. I'm not sure what the best way to structure that would be.

**Comment by daviddias** [comment]
Let's add a section of USAGE for now.

**Comment by Stebalien** [comment]
We should _probably_ add a `SetupNetwork` shared utility function for setting initial latency/bandwidth restrictions.

**Comment by raulk** [comment]
This was documented in https://github.com/ipfs/testground/blob/master/docs/SIDECAR.md. I'm opening an issue to track:

> We should probably add a SetupNetwork shared utility function for setting initial latency/bandwidth restrictions.

As I fully agree we need this.
