### ISSUE TITLE
The line between what is Testground devs responsibility and what is Plan writters responsibility is blurry

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#224]
Me and @nonsense just went over:
- What is the Testground devs responsibility
- What is the Plan writers responsibility
- Where is the cut
- How that is represented in the code

And we found that a few things are getting blurred and mingled. We would like to fix that (and there are simple ways to do so)

Right now, a simple definition of the two responsibilities:

- Testground devs responsibility: Orchestrate Test Plans, Integrate with Github, Create backends for the Plans to run:
- Plan writers responsibility: Specify how a Plan is built (Builders), how a Plan is run (Runners) and what the Plan is testing (Test Cases)

Right now, the lines are blurred because:
- We have a baseline runner strategies parameters that are injected into everyone's Test Plans https://github.com/ipfs/testground/blob/master/env-example.toml#L21-L27
- We have a one size fits all (just that it won't) docker image that plans need to adjust to it. It starts getting tricky when some plans require extra build steps such as pulling specific binaries https://github.com/ipfs/testground/blob/master/manifests/smlbench.toml#L12
- We have variables that aren't being captured by the manifest (such as which registry to push the container)

This means that currently, if we were at the stage where someone was implementing a plan outside of this repo and needed the docker file to do something special, they would have to change how Testground base dockerfile works first.

**We propose that:**
- Plans bring their own Dockerfile
- Plans have all the information about their builder strategies and runner strategies in their manifest. 
- Plans to have a strategy that builds for local run and for builds and pushes to a remote registry. Rather than passing a bunch of build-cfg params on each command

We are ok with having duplicated code per plan (i.e. we expect that a bunch of runner and builder strategies will be similar, that's ok).

**Comment by jimpick** [comment]
It's sort of nice to not have to write a Dockerfile for a testplan if all it needs is a basic one.

On the other hand, it's also nice to be able to stuff extra stuff into a Docker container for many situations.

One idea I had would be to leverage a multi-stage Dockerfile where a base "standard" build would be done as an initial stage, and then the individual testplans could add files as subsequent stages. Perhaps it could be implemented as a new builder? 

https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by raulk** [comment]
Thoughts:

* smlbench and sdk/iptb were an MVP thing; they should not be used in this way. 
* I'll suggest removing this test plan and this sdk module.
* with compositions, builders and runners are not implicitly picked up any longer.

This issue is hard to action on in its current form. It's more of a braindump than requested features/changes.

In the future, it would be better to open smaller issues for each requested change.

**Comment by raulk** [comment]
Note: I don't understand how plans bringing their own Dockerfile would help solve the issues that were identified.

Re: pushing of images, yes, the line is blurry between the `docker:go` builder and the `cluster:k8s` runner; not sure how that translates to the division between humans that the title hints at.

**Comment by raulk** [comment]
See #646.

**Comment by Robmat05** [comment]
This is a discussion, no actionable items. If actionable items arise, please open new ticket and link this discussion
