### ISSUE TITLE
Improve infrastructure with base AMI image for workers

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#225]
If we decide that we are happy with the current tools we use in terms for infrastructure (docker swarm, filebeat, etc.) we should probably create AMI images for our workers, so that once started, they automatically get added to the docker swarm.

Currently if we want to start 100 worker VMs, we will be installing all the software from scratch to all 100 VMs, and the possibility for failure is quite big. Ideally once we have the `manager` node up, and we know its location, and its token, we should bake an AMI image for the workers.

One problem would be `docker node labels` - these are to be applied only from the `manager` so it has to monitor who is joining the swarm. We don't seem to be using the label much, so maybe we can get rid of them altogether (just an idea).

This is all possible with `packer`, but the way to do it, would be I guess to first create the `manager`, then bake and push the `worker` AMI, and then start `n` worker nodes.

This is similar to what @jimpick had in the initial PR a week ago, but also attempting to get rid of the playbook that does the final configuration change with Ansible.

Ultimately, similar to `k8s`, we want to be able to just add/remove worker nodes simply by creating/destroying VMs through an auto-scaling group or Terraform.

cc @jimpick @raulk feedback is welcome :)

**Comment by jimpick** [comment]
I did like having pre-baked AMI images for the workers, as they can have all the dependencies pre-installed and are quick to spin up. The downside is that the AMI images need to be built and managed somehow and you need different images for each AWS region.

**Comment by nonsense** [comment]
> I did like having pre-baked AMI images for the workers, as they can have all the dependencies pre-installed and are quick to spin up. The downside is that the AMI images need to be built and managed somehow and you need different images for each AWS region.

Agree on all points. I'd say this is not only nice to have, but rather required for larger deployments (any docker swarm having more than 10-15 VMs).

AMI images need to be managed somehow, I don't have much experience with that, so will look into it.

AMI images need to be built - no way around that, but I'd rather we build an AMI once, than running Ansible N times (where N could be >100) and having it break for small % of machines just because a TCP connection got reset or something.

We just need to minimize the number of post operations that need to happen on a given worker once we start an instance from the base AMI -
1. Adding it to the correct Docker Swarm cluster - we need to discover the manager and know its join token.
2. Labelling the worker if necessary

**Comment by nonsense** [comment]
@raulk I suggest we close this, as we are moving away from Docker Swarm.

We could still use our Docker Swarm playbooks to provision a bunch of nodes, so I am not sure we should spend time adding `packer` and optimising it further.

**Comment by raulk** [comment]
@nonsense what's the process to add a k8s worker to an existing k8s cluster?

**Comment by raulk** [comment]
In the past I've used CoreOS, etc. but what route are we taking?

**Comment by nonsense** [comment]
@raulk depends on how you create the k8s cluster I think.
With `AWS EKS` you just change the auto scaling group on AWS, and workers come online, connect to the master, and start all the DaemonSets.
With `kops` which currently we use with AWS (but could also use with Google Cloud and other clouds), it is also a matter of changing the auto scaling group config in AWS.

So this functionality that tools like `kops` and platforms like AWS EKS provide, simplifies our infrastructure :)

**Comment by nonsense** [comment]
Closing this because we are not putting more effort in optimising the Docker Swarm setup and it looks like we won't be building infrastructure around it. No point in adding `packer` images to the picture to speed up infrastructure creation at this stage (or maybe ever).
