### ISSUE TITLE
Containers fail to start when running many replicas

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#226]
Sometimes when running many replicas of a test plan, some of the containers/tasks fail to start with the error: `starting container failed: failed to get network during CreateEndpoint: network pz2x9adwafpuht9mlf8l8sbh3 not found`, resulting in `Dec 10 13:27:08.868328  INFO    task status     {"status": {"complete":192,"failed":8}}` on testground.

I think it is possible that the network create API call returns before the network is available for use.

I ran a test plan targeting a Docker Swarm cluster on AWS with:

```
testground run dht/find-peers \
    --builder=docker:go \
    --runner=cluster:swarm \
    --build-cfg bypass_cache=true \
    --build-cfg push_registry=true \
    --build-cfg registry_type=aws \
    --instances=200
```

Two out of three runs contained failed tasks.

**Comment by daviddias** [comment]
How to reproduce?

**Comment by nonsense** [comment]
> How to reproduce?

I updated the description with the exact command for a plan. Feel free to remove these comments, if they are not needed anymore.

**Comment by raulk** [comment]
Related to general Docker Swarm flakiness (e.g. #269).

Docker Swarm was great to get started quickly and with little friction with distributed tests, but it is known to be flaky. We won't be investing the time to follow up on this issue, and are instead focusing our efforts on Kubernetes as a more robust workload orchestration engine that is proven to cope with the magnitudes of scale we require.
