### ISSUE TITLE
Testground cluster infrastructure monitoring

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#228]
`testground` is currently used by developers from other teams (for example Content Routing) and they need to be able to tell how much their cluster is utilised from an infrastructure perspective - therefore need basic monitoring cluster-wide:

- [ ] how many nodes are part of the cluster
- [ ] what is the health of the cluster
- [ ] how much resources (CPU and memory) are requested and what is the actual utilisation per node
- [ ] how much individual pods and namespaces have requested and what is their actual utilisation
- [ ] how much local disks and network are utilised

---

- [ ] once a cluster for `testground` is installed with `install.sh`, we should get out of the box meaningful Grafana dashboards (or other dashboards, such as the Kubernetes dashboard) that convey the information listed above.
- [ ] there should be docs on how to get to those dashboards, so that developers are aware of their existence and know how to access them
- [ ] we need to be able to tell if we are over- or under-utilising a given cluster.

---

I think a good example and something to strive for are the dashboards at https://protocollabs.grafana.net/

**Comment by olizilla** [comment]
We're using prometheus
+ node_exporter for machine metrics 
+ prometheus exporter baked to ipfs
+ mtail` for aggregeating metrics out of logs like nginx access/

I'd use prometheus + cAdvisor for grabbing metrics from docker.

@stongo and the fil-infra has a influxDB + telegraf set up for the same thing.

**Comment by raulk** [comment]
@nonsense low prio -- what tooling would you recommend for k8s?

**Comment by nonsense** [comment]
@raulk I would like to have a look at what the Infra team has setup, maybe @olizilla can give me a quick overview/tour at some point in the coming weeks.

Now that we have moved to Kubernetes, at least it has some out of the box monitoring support with packaged installations that will cover >80% of our needs, some examples on the monitoring part can be found at `https://github.com/ethersphere/swarm-kubernetes`.

I'd like to avoid having to write and configure playbooks from scratch and re-use something as quickly as possible that gives us decent monitoring, and we can iterate from there on.

**Comment by coryschwartz** [comment]
Kops has built-in addons that can be added in the yaml file, but unfortunitely can't be added in the commandline by kops create. The built-in ones are these https://github.com/kubernetes/kops/tree/master/addons

One way to do this is by creating the and editing a kops cluster manifest like in https://github.com/ipfs/testground/pull/534

If this method seems appealing, you can add other addons, including the charts we currently install.

The pros of doing it this way is that `kops validate` includes addons and we can have a known good yaml. The installation is a single step.

The cons of doing it this way is that you would still want to edit the config file, even if  only to change the name of your cluster.

Another way to do this is to add the monitoring just by adding a few more steps in the install script.

**Comment by nonsense** [comment]
This repo is also a good solution: https://github.com/coreos/kube-prometheus - the number of dashboards it comes up with is quite elaborate.

**Comment by nonsense** [comment]
This issue also includes having meaningful dashboards, and right now this is not the case - we should review the dashboards we have available from K8s dashboard and from Grafana, and decide if this is good enough for a start, and remove the useless dashboards.

Currently there are a few dashboards in Grafana that don't show any data and are confusing:

<img width="1178" alt="Screenshot 2020-02-25 at 13 50 41" src="https://user-images.githubusercontent.com/50459/75249338-6a85e880-57d6-11ea-8846-c0363e1436e5.png">

<img width="1340" alt="Screenshot 2020-02-25 at 13 51 12" src="https://user-images.githubusercontent.com/50459/75249351-72458d00-57d6-11ea-8758-ee879d25181e.png">

<img width="1670" alt="Screenshot 2020-02-25 at 13 52 10" src="https://user-images.githubusercontent.com/50459/75249363-77a2d780-57d6-11ea-8957-6490ea0dd7db.png">

<img width="1676" alt="Screenshot 2020-02-25 at 13 52 40" src="https://user-images.githubusercontent.com/50459/75249383-7f627c00-57d6-11ea-8a55-73abd4b1ca08.png">

<img width="942" alt="Screenshot 2020-02-25 at 13 53 04" src="https://user-images.githubusercontent.com/50459/75249389-84273000-57d6-11ea-9373-4a74f90a5593.png">

The `Nodes` dashboard is the only one that shows somewhat meaningful data right now, for the rest, half of the panels are empty.

**Comment by nonsense** [comment]
@coryschwartz and @raulk - I updated the description for this ticket with a few concrete points on what I think we need from an infrastructure monitoring perspective.

I believe @coryschwartz has done most of the initial work, but I think the end result is not there yet - namely:
- docs on how to access Kubernetes dashboard
- meaningful dashboards in Grafana (some of these might be part of the Kubernetes dashboard, and this is fine, but we should know where to look for what) - half of the dashboards in Grafana are empty (see screenshots). I've had similar experience with out-of-the-box installation for Kubernetes monitoring in the past, so I am not surprised we need adjustments there.

**Comment by coryschwartz** [comment]
Closing, complete.

**Comment by nonsense** [comment]
I am not sure why this is closed, or if I am doing something wrong.

I can't find much of any actual utilisation in the dashboards. I also saw commits for Weave and Redis monitoring, but I don't find dashboards for these either.

CPU usage and Memory usage panels in pretty much all dashboards are empty for me.

@coryschwartz could you maybe do a demo of what you are seeing on your end, so that it is clear to everyone on the team what kind of infra monitoring we have. Currently we only have the following in the README:

```
$ kubectl -n monitoring port-forward service/grafana 3000:3000
```

And opening up Grafana seems to be pretty much useless without meaningful dashboards.

**Comment by Robmat05** [comment]
Sliding this to v0.4 milestone. I expect that this may be able to close once demo’d

**Comment by coryschwartz** [comment]
@nonsense I added dashboards to /dashboards and a tool for importing them.

I saw that today too that some of the dashboards are now not receiving data.

In order to complete the kubernetes upgrade, I'm going to have to move the monitoring away from the kops addon, and I suspect the glitchy default dashboards will go along with it.

**Comment by Robmat05** [comment]
@coryschwartz So, did you reach out and put this ticket into progress?

**Comment by nonsense** [comment]
@coryschwartz great! We need to add the dashboards as part of the installation, or as a one line command, because adding them manually for every cluster is trouble:
- [ ] after grafana and prometheus are up, add `data source` to grafana (could be done with `terraform` or your import tool) pointing to prometheus (the `kops addon` is doing that somehow)
- [ ] after `data source` is added in grafana, import all committed dashboards (could be done with `terraform` or your import tool)
- [ ] it'd be nice to remove authentication in grafana altogether. we don't need to set user/pass (or skip setting it) on every new cluster - we are behind the kubernetes proxy after all.

I am up for moving monitoring away from `kops addon`, because I have the feeling we will most probably drop or change some of the default dashboards as they are not really working - I don't know of a way to do that through the `kops addon`.

**Comment by coryschwartz** [comment]
Since a few days ago, we have moved away from the kops addon and onto helm charts. The grafana dashboards are uploaded automatically. There is one runner which doesn't start grafana automatically, the local:exec runner, and will be fixed once its merged.
