### ISSUE TITLE
DHT find_peers distributed test over 1000 nodes

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#23]
A test scenario that we'll use as an example/template to build the system gradually.

1. Initially this will run within a single process.
2. Run as multiple processes locally, coordinated by the sync service (Consul). Local test runner.
3. Deploy to a Nomad cluster. Nomad test runner.

**Comment by daviddias** [comment]
Work on specing tests at #33

**Comment by daviddias** [comment]
Needs https://github.com/ipfs/testground/issues/103 to get access to those 1000 nodes

**Comment by daviddias** [comment]
This is now possible. Note for the reader, we are not using neither consul or nomad (spec is out of date at the moment). Check the tutorial on the README to learn how to run the find_peers tests and how to setup a cluster for yourself https://github.com/ipfs/testground#contributing--testing
