### ISSUE TITLE
Redis write/subscribe race

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#252]
#### Description:

The DHT testplan currently fails randomly, waiting for bootstrappers to appear (in `getBootstrappers`). However, the bootstrappers are clearly registering themselves.

I've noticed a key difference between how we write bootstrapper records versus peer records:

* For peer records, we always _write_ a peer record before we subscribe.
* For bootstrap records, non-bootstrappers will subscribe without writing.

That means, for bootstrap records, we may subscribe to a key that hasn't been written yet. I'm guessing we have some kind of race in our subscription logic for keys that are being written for the first time while another node is concurrently subscribing to the record.

**Comment by raulk** [comment]
Can you enable debug log level? `--run-cfg log_level=debug` The sync service has comprehensive logs at info and debug, so that'll give us better insight.

**Comment by raulk** [comment]
Another question: when this happens, do you get _no_ bootstrappers at all, or less than have theoretically enrolled?

**Comment by Stebalien** [comment]
> Another question: when this happens, do you get no bootstrappers at all, or less than have theoretically enrolled?

We've only tested with one. We should test with more.

**Comment by hacdias** [comment]
This is an exhausting (but still trimmed) log of a run where [4/5 failed](https://gist.github.com/hacdias/7aca77d40845b95c3f6b5e715edea16f). By looking at it carefully, I noticed that:

1. The message was sent before **anyone** else started subscribing.
2. There are some that fail and those are the same that printed `eligible key count: 0`.

**Comment by hacdias** [comment]
According to what I'm reading, Redis does not guarantee delivery, nor access to previously sent values before subscribing. I don't actually understand how we're fetching them now.

however, I saw something about streams: https://redis.io/topics/streams-intro that might be useful.

https://stackoverflow.com/questions/23675394/redis-publish-subscribe-is-redis-guaranteed-to-deliver-the-message-even-under-m

**Comment by raulk** [comment]
@hacdias entries are stored as keys, and when we subscribe to a subtree, we subscribe via PubSub, and synchronise the existing state by replaying what's in the sorted set in Redis, and reconciling it with the pubsub messages we receive.

**Comment by raulk** [comment]
This was fixed by migrating to Redis streams in #308.
