### ISSUE TITLE
Support more than 254 nodes

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#283]
Currently, docker assigns a single C block by default. However, we really want a B block.

Unfortunately, we can't just assign the same block to all nodes, even if the networks are never connected, because docker just doesn't allow this :rage:.

So I'm going to coordinate IP address assignment via redis. For now, the test runner will increment a number in redis and use this to allocate a class B block. It will then communicate this block to the test via the test runtime.

**Comment by raulk** [comment]
@Stebalien @nonsense Is this still relevant with our new k8s setup? For the `local:docker` runner, we could limit the number of instances to 254.

**Comment by Stebalien** [comment]
This is no longer true for any of our runners, as far as I know. We now assign a B block.
