### ISSUE TITLE
Document how to set up and use the Docker Swarm runner with a Cluster

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#292]

**Comment by nonsense** [comment]
@daviddias setting up a Docker Swarm cluster is documented at `infra/docker-swarm/README.md` and we went over it with @jimpick 

Using Testground with it, is not fully merged, but if you want this done, @raulk can check the https://github.com/ipfs/testground/pull/217

**Comment by raulk** [comment]
While we are abandoning efforts related to Docker Swarm, if we still offer the runner (despite deprecating it), we certainly should ensure that it's properly documented.

Based on @nonsense's comment above, it feels like this is done, so I'm proceeding to close.

**Comment by nonsense** [comment]
Yes, the current state of the Docker Swarm infra is documented.
