### ISSUE TITLE
Get Docker Swarm Runner to be operational and useful to go-ipfs/go-libp2p Core Contributors

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#293]
As we make progress with the k8s runner and its networking configuration, we want to have the Docker Swarm Runner ready to spawn a small testbed of 200 instances (minimum 100) for the go-ipfs and go-libp2p developers to use for testing.

We understand (well) that Docker Swarm won't scale to thousands of instances (we've tried and debugged to no avail). However, there is still value on finalizing this runner as it will grant us to use Sidecar (already implemented), enabling tests to have a network configuration (latency, jitter, bandwidth)

**Comment by raulk** [comment]
We have decided to invest all our efforts in the cluster:k8s runner.
