### ISSUE TITLE
Test Istio with k8s

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#294]
https://istio.io/

**Comment by raulk** [comment]
@nonsense mind providing a status update here? I believe we've made our CNI choices and integrated them with Sidecar, but it would be great if you could summarise your findings here if we ended up doing a spike on Istio, or the rationale why we dropped it, if we didn't do a spike.

Personally I think Istio/Envoy are way more application-level focused service meshes. They probably contain some useful network primitives for us, but it seems over-engineered for our use case.

Thanks!

**Comment by nonsense** [comment]
I haven't done any investigation on Istio yet.

**Comment by raulk** [comment]
I'm going to take the liberty of closing this, as I honestly think Istio is a bad fit for us. We need to exert very tight control on the network, and Istio is meant for the opposite: transparent routing and policy enforcement between microservices, so it does a lot of magic behind the scenes.
