### ISSUE TITLE
Test CoreOS Flannel with k8s

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#297]
https://coreos.com/flannel/docs/latest/

**Comment by nonsense** [comment]
Tested it and it works - we can have at least two networks - the default Kubernetes network, and a secondary overlay network, as long as we run multiple `flanneld` daemons on hosts.

**Comment by nonsense** [comment]
Closing, let's continue the conversation at https://github.com/ipfs/testground/issues/295

**Comment by nonsense** [comment]
Note that you need `multus-cni` to attach multiple network interfaces to pods, even if you use `flannel` for both networks.
