### ISSUE TITLE
testground daemon to client streaming is broken/weird

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#306]
Top is client, bottom is daemon. I should be getting all structured output in the client. Instead, I'm getting what's arguably the most uninteresting part only -- the docker build logs.

![image](https://user-images.githubusercontent.com/1101242/71004046-ce5aa980-20e1-11ea-83d9-a5e6020569f7.png)

@nonsense @hacdias let's chat about this.

**Comment by nonsense** [comment]
From your screenshot it looks like `builder` is writing to the `io.Writer`, but `runner` is not.

**Comment by hacdias** [comment]
Gonna see this

**Comment by hacdias** [comment]
But first, what do we **want** to see on each side?

**Comment by nonsense** [comment]
Every `runner` receives a `io.Writer`:

```
func (*ClusterSwarmRunner) Run(ctx context.Context, input *api.RunInput, ow io.Writer) (*api.RunOutput, error) {
```

Some interesting to us messages, such as `network created successfully`, `creating service`, `task status`, etc. are currently written to `stdout` via a `logger`, and not to the `ow io.Writer`, so they are logged only on the daemon side, and not propagated back to the client.

We have to review the individual runners and decide:
1. which messages are relevant only to the daemon and the client doesn't care about
2. which messages are relevant to both and we'd like both logged on the daemon and propagated to the client
3. which messages should only go to the client.

**Comment by raulk** [comment]
Working on this 🤞
