### ISSUE TITLE
migrating sync subtrees to redis streams

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#308]
We are finding some weirdness with Redis keyspace notifications. See https://github.com/ipfs/testground/issues/252. If we are willing to give up ZooKeeper-like ephemeral nodes, adopting Redis streams is a good option as it would greatly simplify the subtree watch/write logic of the sync service.

Related:

https://github.com/ipfs/testground/pull/263#issuecomment-565575281
https://github.com/ipfs/testground/pull/263
https://github.com/ipfs/testground/issues/27

**Comment by raulk** [comment]
Design:

* The API remains the same. Only the implementation changes.
* We preserve the subtree construction.
* Stream keys: `run:<run id>:plan:<plan id>:case:<case id>:<subtree key>`.
* Adding entries happens with a transaction using `XADD` and returning `XLEN`. The latter is our seq.
* Consuming messages happens with `XREAD` with start index 0. We use the `BLOCK` option to block on new entries.
* We don't want to keep the streams lingering, so for now let's set TTLs on the entire stream. Every 5th node participating in a subtree (mod 5) will be responsible for bumping up the TTL of the stream by 30 seconds.

@hacdias

**Comment by hacdias** [comment]
What's missing from #263 apart from returning Xlen?
