### ISSUE TITLE
Throttle the initialization of instances

### ISSUE THREAD

**Issue by lanzafame** [ipfs/testground#315]
## Description

Currently, the initialization of a large number (>1000) of instances puts a significant amount of load on the underlying hardware. There is no need for the initialization phase of the test instances to be done as quickly as possible (faster is better but not at the cost of bringing down the host machine). Also, thinking about the real world scenario of ipfs and p2p networks in general, 10s of thousands of peers are not all spinning up and connecting to each other in the same second. 

## What defines this endeavour to be complete?

<!--Create a check list of what you expect to see as part of delivering on the ask--

- [ ] plans batch initialize test instances

**Comment by raulk** [comment]
@lanzafame what runner was this for?

**Comment by Robmat05** [comment]
This has been returned to the Author to open new issue if applicable. Closing as Discarded pending new issue.
