### ISSUE TITLE
Docker Swarm logging breaks all service logging on cluster, requires reprovisioning

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#319]
I encountered some very strange behaviour with Docker Swarm that was making development against the cluster very difficult. I didn't understand what was happening, and it was enough of a blocker to my test work that I spent more than a day trying to characterize the problem and isolating it.

After running my test (basic-tcp/upload) using the `cluster:swarm` runner, I was not able to view the log output, either in the testground daemon output or using `docker service logs <name>`.

Even worse, after running the test, I am no longer able to view the logs of any service using `docker service logs <name>`.

I am still able to ssh into the individual worker machines, and use `docker logs` to view the individual container logs, but `docker service logs` will not return a unified set of logs. This makes retrieving results from a test run on a cluster difficult, as it becomes necessary to log into each machine individually to view the logs.

This can be easily verified by running a service:

```
docker service create --replicas 1 --name helloworld alpine ping docker.com
```

If the cluster is in the "broken" state, then running the following:

```
docker service logs helloworld
```

... will not show any results.

It appears that once the cluster is in this state, it doesn't appear possible to fix it. Rebooting all the machines will not repair the cluster so that `docker service logs` will work again. It's unclear what the core problem inside Docker is, but it appears that some internal state related to service logging has been corrupted. This appears to be a [common complaint](https://github.com/moby/moby/issues/33183) with Docker Swarm - likely an upstream bug.

In the process of trying to get to the bottom of the issue, I tried an alternate version of Docker - the version of Docker that ships with Ubuntu 19.10 instead of docker-ce, in the hopes that it might have just been related to the particular version we were running, but `docker service logs` would stop working every time. It was very confusing, as `docker service logs` would work fine up until the moment I tried to use testground with the cluster.

After re-installing the cluster literally dozens of times (thankfully not so difficult thanks to the work on Terraform + Ansible), I was able to trace the moment that `docker service logs` stops working to the point in the cluster:docker runner where it subscribes to the service logs using cli.ServiceLogs()

https://github.com/ipfs/testground/blob/d36c1df5a8e288175dc4462b4501cc723927714d/pkg/runner/cluster_swarm.go#L288

Once that code path is executed, `docker service logs` will not work again in the cluster for any service.

The simplest workaround in order to unblock using Docker Swarm with testground and preserve the ability to use `docker service logs` in the future is to pass `--run-cfg keep_service=true` to testground. This avoids running the code that corrupts the cluster. It is then possible to use `docker service logs <name>` from the command line to view the results. Of course, the service and related network should be manually deleted afterwards.

I think it will be difficult to debug the source of the problem further without getting into the Docker source code. Given that we are evaluating using k8s instead of Docker Swarm, it's probably better to use the workaround. It might be a good idea to disable the cli.ServiceLogs() code path as that will break `docker service logs` on the cluster permanently, and I know of no way to fix it without reprovisioning the cluster.

**Comment by raulk** [comment]
Docker Swarm was great to get started quickly and with little friction with distributed tests, but it is known to be flaky. We won't be investing the time to follow up on this issue, and are instead focusing our efforts on Kubernetes as a more robust workload orchestration engine that is proven to cope with the magnitudes of scale we require.
