### ISSUE TITLE
Shall we disable codecov from being run in CI on every commit?

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#321]
I think this is a discussion that we should have as a team:

**Do we want codecov to be run as part of CI and to mark the state of Testground as broken when it fails?**

<img width="1177" alt="Screenshot 2019-12-23 at 16 28 49" src="https://user-images.githubusercontent.com/50459/71366307-f0e93880-25a1-11ea-8644-8c013b4725e1.png">

I personally find the current CI setup problematic, because:
1. It looks like the project has a broken master branch, which is not a good development practice. (see screenshot)
2. PRs appear as they are failing CI, and a reviewer has to check individually all PRs that they are marked to review, to determine if an `optional` (codecov) check is failing, or a `required` check is failing.

I think that code coverage is useful in finding untested parts of our codebase, but I don't find the actual numeric measurement very valuable. Therefore I find that tying our CI success/failure with the numeric measurement is actually counterproductive.

Another point worth mentioning is that it seems we are still in the MVP phase of the project - we have a high level overview of what we want to build and we have an idea of where we want Testground to go in the future, but we haven't locked the tools we will need to achieve that. Do we need `cluster_swarm.go` to be covered with tests, if we might drop Docker Swarm support in a month? Do we need `cluster_k8s.go` to be covered with tests, if we might drop Kubernetes support in favour of Nomad runner in another month? I think it should be up to code reviewers to determine the answers to these questions during code reviews, rather than have an automated system telling us that we are a few % short of the necessary code coverage.

Interested in your opinions @daviddias @hacdias @jimpick @raulk @Stebalien

**Comment by hacdias** [comment]
@nonsense personally, I don't mind removing Codecov from the PR/Commit status. I would just keep it on the README though.

**Comment by nonsense** [comment]
> @nonsense personally, I don't mind removing Codecov from the PR/Commit status. I would just keep it on the README though.

If we can have it on the README without it being run on every commit and changing the build status, that'd be great - it would remind us all the time about the code coverage!

**Comment by Stebalien** [comment]
* We should exclude parts of the project that are tested via integration tests. Ideally, we'd calculate code coverage for integration tests but that's a bit tricky.
* I'd set the _failure_ cutoff to the current code coverage so we avoid regressions.

**Comment by raulk** [comment]
Personally, I think _quantitative_ coverage should be an _informational_ indicator, both on PRs and README, with engineers making _qualitative_ sense of the coverage analysis.

**Comment by nonsense** [comment]
@Stebalien @raulk not sure I understand how to translate your comments into actionable tasks that will fix our CI.

@Stebalien our current code coverage is 2%, you mean we should add a cut-off at 2% ? I don't see much value in spending time adjusting CI at that level, but we might disagree :)

@raulk the coverage is not just an informational indicator right now, it is marking our CI builds are red, hence this question here.

I see 3 options in general, feel free to suggest another:
1. We do nothing, and continue to ignore that half of our builds are red because code coverage.
2. We enforce a rule that we don't merge red PRs and start fixing improving code coverage (this will distract us from other tasks, but it is an option).
3. We disable codecov from being run in CI on every commit, and keep it on in the README
4. ...?

I am not happy with 1. personally, although I can live with it :) It has been like this for a month or so. 2. also seems like a distraction at this stage of the project. Therefore I suggested 3.

**Comment by raulk** [comment]
Concretely, I mean setting the “informational” flag to true in the codecov config: https://docs.codecov.io/docs/commit-status We are not paying sufficient attention to quantitative coverage right now. We’re iterating rapidly, and aren’t taking any deliberate steps to ensure unit testability of the components we implement, to begin with. Pursuing coverage under this circumstance is starting the house from the roof. I much rather focus on velocity and implementing missing features at this point, for which a suite of coarse-grained integration tests will suffice (itest) to pinpoint behavioural regressions.

A comprehensive suite of unit tests with maximal coverage is our end goal, but our system is not ossified enough. The cost of maintaining unit tests against a morphing target is detrimental at this stage.

**Comment by nonsense** [comment]
Thanks, @raulk . I agree with everything said. Opened a PR for this at https://github.com/ipfs/testground/pull/324 (would have done it earlier if I knew about that flag).

**Comment by nonsense** [comment]
I guess I messed up, or we are misunderstanding how the `informational` flag works, because `codecov` is still reporting failures on our CI.

**Comment by hacdias** [comment]
From the docs:

> Use Codecov in informational mode. Default is false. If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified. Informational mode is great to use if you want to expose codecov information to other developers in your pull request without necessarily gating PRs on that information.

I would say that the informational only applies to PRs. However, I've not been seeing Codecov checks on PRs. Only on branches, which is odd.

**Comment by nonsense** [comment]
@hacdias not sure why PR such as https://github.com/ipfs/testground/pull/415 is failing then... Travis is passing, and Codecov is read, even though `informational` flag is set to true?

**Comment by hacdias** [comment]
Thar PR shows me this:

![image](https://user-images.githubusercontent.com/5447088/73349516-35dc4b00-4283-11ea-8ba5-72cf7916784c.png)
