### ISSUE TITLE
ensure testground starts correctly on local dev machine

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#333]
## Description

At the moment there are a few things that we take for granted when we start `testground` -
1. That `control network` and `testplan networks` are not going to collide with existing networks (on my local machine `control network` couldn't be created until I changed its CIDR.)

2. On Dirk's machine, `testground-redis` was running, but was not attached to the `testground-control` network so it was not discoverable, and testground was failing.

## What defines this endeavour to be complete?

I am not sure what exactly this issue entails, but we need a better way to enforce reproducibility on devs' machines, because some of these errors are not obvious and we end up with a lot of local state from one machine to another that is changing testground behaviour from one machine to the next.

**Comment by raulk** [comment]
The `testground terminate` and `testground healthcheck --fix` commands fix this.
