### ISSUE TITLE
Introduce a "runner init" method to cleanly setup the environment

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#339]
Currently, each runner does a bunch of "is this setup? no, let's start X, create network Y, etc...". Unfortunately, this means we'll, e.g., leave old, outdated networks/containers as-is if they already exist.

Instead, we should:

1. Introduce an "Init()" method to each runner, to be called once when the runner is first invoked.
2. The init method should _delete_ any existing testground containers.

Note: the old behavior existed because we didn't _have_ a daemon and didn't have any way for test runs to coordinate. That's no longer the case.

**Comment by raulk** [comment]
We won't be introducing a runner init method. Instead, these preconditions will be checked in the healthcheck flow.

**Comment by raulk** [comment]
Healthchecks were implemented in v0.2, removing the need for a dedicated init method.
