### ISSUE TITLE
Support hashicorp/go-getter to fetch the source of a test plan

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#34]
This will enable us to host the source for test plans externally, e.g. in GitHub, rather than in a monolithic repository.

In the test plan manifest, we should use go-getter URLs for the `source_path` field.

**Comment by hacdias** [comment]
I was looking into this, but I got confused. Isn't this already implemented?

https://github.com/ipfs/testground/blob/84453952a3760c6dbf1cb5379bd0883116d5f7cb/pkg/build/golang/exec.go#L63-L85

https://github.com/ipfs/testground/blob/9c0992c091dbd4fc2e876a9f4938cae1c8d56a00/pkg/build/golang/docker.go#L120-L150

**Comment by hacdias** [comment]
It does work: I changed  `source_path` of chew_datasets.toml to

```
source_path = "git::https://github.com/ipfs/testground.git//plans/chew-datasets"
```

and it works!

**Comment by raulk** [comment]
Yes, I had already implemented this. Well spotted!
