### ISSUE TITLE
Test plan executables should generate nomad HCLs for test cases

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#35]
We want the HCL definition of a nomad test case to be co-located with the test case itself. The way to achieve this is to have the test plan executable print the HCL to stdout. 

Introduce a `TEST_COMMAND` environment variable that can take values: `run`, `schedule`.
  - When the value is `run`, the executable will run the test case designated by `TEST_CASE_SEQ`, as normal.
  - When the value is `schedule`, the executable will spit out the Nomad HCL for scheduling the test case designated by `TEST_CASE_SEQ`, with the parameters conveyed in other environment variables.

The emitted HCL may in itself be a Go template, as there are certain elements that cannot be determined by the test case itself (e.g. test run ID, etc.). We'll need to define the expectations and input/output clearly here.

**Comment by daviddias** [comment]
Not using Nomad anymore
