### ISSUE TITLE
Sidecar <-> k8s follow-up tasks

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#351]
There are a few follow-up tasks that we identified when working on the first iteration of the sidecar <-> k8s runner. These should be addressed soon:

- [x] confirm security privileges for initContainer that sets up route to k8s services CIDR
Result: we need security privileges for the initContainer due to `ip: RTNETLINK answers: Operation not permitted`. I don't really see an issue with giving full security privileges, as we just run one command, but we could probably restrict here.
- [x] check how to change default Weave network to 16.x.x.x - 32.x.x.x - probably `IPALLOC_RANGE`
- [ ] auto select a good network (ideally in the range 16. - 32. to match docker.)
- [ ] fix code which gets next available network - right now we have `10.33.10.0/24` hardcoded in `cluster_k8s.go`
- [ ] consider simplifying code that drops routes other than Redis in control network and the hardcoded podCIDR block - `100.96.0.0/11`. If we can't this needs to be documented with high visibility as it is not at all obvious!
- [ ] consider changing control network CIDR when running `kops`
```
The field in the clusterSpec, .NonMasqueradeCIDR, captures the IP range of the cluster.
Within this IP range, smaller IP ranges are then carved out for:
Service IPs - as defined as .serviceClusterIPRange
Pod IPs - as defined as .kubeControllerManager.clusterCIDR
```
- [ ] maybe do a demo for @dirkmc , @aschmahmann and other people, and gather more feedback.

**Comment by nonsense** [comment]
@raulk this seems to be duplicating with some of the issues you created. Shall we close it?

I thought we don't need granularity per checkbox item, but since you already created individual issue for each, we might as well use it.

**Comment by raulk** [comment]
Oops! I didn’t see this one. Yeah, we don’t need it but it’s more motivating to always be shifting cards to the right :-)

**Comment by nonsense** [comment]
Closed since we have individual issues for all of these, but the `demo`, which we must do sooner rather than later, and I will make sure we communicate and arrange soonish.
