### ISSUE TITLE
Change default Weave network to 16.x.x.x - 32.x.x.x

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#356]
Carried forward from https://github.com/ipfs/testground/pull/336.

**Comment by nonsense** [comment]
This can be done with `IPALLOC_RANGE` Weave env flag.

Tested and resulted in:
```
        Service: ipam
         Status: ready
          Range: 16.0.0.0/4
  DefaultSubnet: 16.0.0.0/4
```

Scheduled two containers and they are still reachable, so it looks like it works as expected.
