### ISSUE TITLE
Simplify control network blackhole routes

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#359]
Consider simplifying code that drops routes other than Redis in control network and the hardcoded podCIDR block - 100.96.0.0/11. If we can't this needs to be documented with high visibility as it is not at all obvious!

Carried forward from https://github.com/ipfs/testground/pull/336.

**Comment by raulk** [comment]
@nonsense could you post an update here, please? Trying to close the v0.1 milestone. Thanks!

**Comment by nonsense** [comment]
I think we are fine with this as it is.

Sidecar runners are coupled with the environment - I don't see a way of fixing this, without doing magic, and I'd rather not do that.

If we have to change the default podCIDR for some reason in the future, we will also refactor the sidecar k8s runner.
