### ISSUE TITLE
Create a frictionless one-stop experience to bootstrap and manage a k8s cluster

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#367]
We want the developers using testground to not have to fiddle with setting up a k8s cluster.

The experience of doing so should be streamlined and frictionless, i.e. one or two scripts, testground commands, etc. @nonsense has already been striving to make this so since the beginning, but this issue elicits that expectation.

## Definition of done

- [x] It is possible to create and teardown a k8s cluster with a single command, or very few commands.
- [x] It is step-by-step documented.
- [ ] User acceptance test: rope somebody in from the team, and have them go through the docs.
- [x] It works consistently every time.

**Comment by nonsense** [comment]
Here is a demo of this setup:
1. Download https://drive.google.com/open?id=1p8RqDv7tyqJH0V6uOpLEtBvaa_fU2zjg
2. `asciinema play -s 3 ./demo2.cast`

This was recorded a while ago, before fixing the data plane, but the steps are exactly the same as now, and you can see how to spin up a Kubernetes cluster.

I believe the README at https://github.com/ipfs/testground/tree/master/infra/k8s is very up-to-date, so I welcome anyone who wants to try it!

**Comment by raulk** [comment]
@dirkmc has agreed to help us UAT test the step-by-step guide, to close the loop here. Thanks!

**Comment by dirkmc** [comment]
I made a PR with a couple of suggestions for the README but LGTM :+1: 🎉

**Comment by nonsense** [comment]
We've removed some steps and added others. I think the experience in general improved since @dirkmc checked this.

**Comment by raulk** [comment]
Several people have now used the instructions, with successful results. I'm considering this issue done.
