### ISSUE TITLE
cluster:k8s runner: consolidate stdout logs with EventManager via `kubectl logs`

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#370]

**Comment by nonsense** [comment]
I guess this could be the next step for https://github.com/ipfs/testground/pull/440/files

**Comment by nonsense** [comment]
@raulk you are working on this AFAIK, feel free to return to me if this needs more attention after your outpus revamping PR lands on `master`.

**Comment by raulk** [comment]
The whole thing was refactored and merged in https://github.com/ipfs/testground/pull/467.
