### ISSUE TITLE
Self prometheus scraping and snapshotting (was: sdk: convenience functions to emit go runtime metrics)

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#372]
This issue originally had to do with capturing snapshots of go runtime metrics and saving them as raw output assets.

In the process, we realised that Prometheus already instruments go runtimes and exposes metrics, automatically. Additionally, various libraries/projects that Testground caters to use Prometheus to export metrics.

Therefore, there's an opportunity to create a lot more value if we implement this correctly.

- [ ] In the runtime sdk, create a function that initialises a default Prometheus http handler: https://prometheus.io/docs/guides/go-application/, exposing it on some local port, and returning that address.
- [ ] In the runtime sdk, create a function that polls a provided HTTP address every N `time.Duration` (argument), and writes the output of each iteration as a raw asset (`runenv.CreateRawAsset()`) following some user-provided filename pattern.

Voilà. Folks wanting to export Go runtime metrics (and all Prometheus metrics), can just call:

```go
addr := runtime.MustExportPrometheus()
go runtime.HTTPPeriodicSnapshots(addr, 5 * time.Second, "metrics.out")
```

--- 

Note: we may run into problems with the way that automatic asset closure has been implemented (we can only track 32 assets per type). This needs to be rethought, as in this case we'll create an asset, write to it, and close it immediately (it won't be a long-lived asset).

**Comment by hacdias** [comment]
I'm going to start this. But first, I'd like to settle in on how are we going to emit the metrics: Should we use a separate JSON file? Or use `runenv.RecordMetric`?

**Comment by raulk** [comment]
@coryschwartz and @nonsense are working to implement statsd/Prometheus collection. Prometheus already exports go runtime metrics: https://prometheus.io/docs/guides/go-application/ what I suggest you do here is use the Prometheus library to expose the /metrics endpoint, then set up a timed goroutine to take snapshots periodically (e.g. every 5 seconds, configurable) and save them into raw assets with the new runenv APIs.

**Comment by raulk** [comment]
@hacdias I transformed this issue (title and description) to describe the approach we want to take here.
