### ISSUE TITLE
all runners: inject TEST_OUTPUT_FILE_PATH env var with location to write files

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#374]
This value should be set by the runner. Why? Each runner will have a different strategy. k8s will want to ship logs to a networked volume, e.g. S3, whereas the local runner will be fine storing assets in the local filesystem.

_Note: looks like #409 implemented some of this._

What is missing is the following:
- [x] local:exec runner.
- [x] cluster:k8s runner (sync with @nonsense).
- [ ] rename `TestArtifacts` to `TestAssetsDir`.

**Comment by hacdias** [comment]
Just PRed for the first and last points (#431).

@nonsense how'd you this for kubernetes? I presume there should be some kind of mounting on the `jobRequest`?

**Comment by nonsense** [comment]
@hacdias I opened a draft PR at https://github.com/ipfs/testground/pull/433 , which works on small number of machines, but needs to be load tested and ran with at least 1k containers on 15-20 VMs.

**Comment by raulk** [comment]
This was closed in https://github.com/ipfs/testground/pull/467.
