### ISSUE TITLE
cluster:k8s runner: attach the chosen network storage to pods

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#375]

**Comment by nonsense** [comment]
We currently attach a shared S3 bucket to all hosts in the cluster and all pods write `artifacts` to a directory on that bucket.

**Comment by raulk** [comment]
@nonsense based on the above, it seems like this can be closed. This feature was introduced in https://github.com/ipfs/testground/pull/433. (Don't forget to add a "Fixes #..." keyword in the PR, which will auto-close the corresponding issue once merged.)
