### ISSUE TITLE
`testground collect <run_id>` command to collect all assets from a run into an archive

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#376]
Here's what I'm thinking:

* `testground collect --runner cluster:k8s <run_id>` should call a new `CollectOutputs(<run_id>)` method in `api.Runner`.
  * The logic for collection is runner-dependent, e.g. the cluster:k8s runner (running in AWS) will download from S3, while the local runner will harvest those files from the filesystem.
* `testground collect` would produce a zip file, with the following layout:

```
/
|___ <group id> (coming from the composition)
|      |____ <instance id, could be container name or index>
|                     |__ stdout.json
|                     |__ stderr.json
|                     |__ dht_events.json
|                     |__ heap.out
|                     |__ cpuprofile01.out
|                     |__ cpuprofile02.out
|                     |__ cpuprofile03.out
|                     |__ swarm_state.json
|      |____ <instance id, could be container name or index>
|      |____ <instance id, could be container name or index>
|      |____ <instance id, could be container name or index>
|___ <group id> (coming from the composition)
|      |____ <instance id, could be container name or index>
|      |____ <instance id, could be container name or index>
```

**Comment by hacdias** [comment]
Given the `run_id`, isn't it ambiguous which plan it refers to? I know each run_id is unique, but right now we're storing the assets in a `plan/run_id` structure, which makes this harder to find.

I can, though, flatten the directory and just have `run_id` which makes this quite easy. What do you think @raulk?

**Comment by nonsense** [comment]
@hacdias not sure what you mean with ambiguous, as `run_id` is indeed unique.

You have a point about the `plan/run_id` structure though - and note that this is `runner` dependent, so we should probably be passing the runner to this command as well.

On the PR adding this to k8s, I save them under `run_id` directory first: https://github.com/ipfs/testground/pull/433/files#diff-4b36ef203136c9b393fad256dee9758cR192

**Comment by hacdias** [comment]
> @hacdias not sure what you mean with ambiguous, as run_id is indeed unique.

The way to get there, as you said on the second paragraph 😅 

> It will be a good idea to standardize this across runners

Yes! That's why I actually created these [two functions](https://github.com/ipfs/testground/pull/431/files#diff-7e57a64996eb40733c4bed159160297aR33-R47). We could add one more for the actual assets path and another for the logs and ensure we use those everywhere.

**Comment by nonsense** [comment]
Is this issue about collecting:
1. artifacts/assets
2. outputs (stdout, stderr) - structured output from Testground
3. both?

**Comment by raulk** [comment]
This was closed in https://github.com/ipfs/testground/pull/463.
