### ISSUE TITLE
reliably run DHT test plan with 1k instances with k8s and sidecar k8s runner

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#379]
We need to make sure:

- [x] Sidecar doesn't fall over.
- [x] Redis keeps up. Pay careful attention to sync service timing issues.
- [x] We don't run into CPU contention issues.
- [x] We don't run into weird network communication issues.

Ideally, we'd run the DHT find peer testcase. However, we may want to start with a simpler "connect everyone in a ring" test case.

**Comment by nonsense** [comment]
I believe this is done.

The `dht/find-peers` test plan does NOT return `outcome: ok` for peers when ran on 1000 instances, but, `sidecar`, `weave`, `redis` do not return any errors. This appears to be a problem on the testplan.

Switching between 1000 and lower number of instances (for example 60), results in one passing, and the other timing out, which is what we'd expect... `sidecar` seems to be handling requests for network management fine.

**Comment by raulk** [comment]
DONE! We believe any remaining flakiness is due to the test plan logic itself, not to the k8s/sidecar/networking infra.
