### ISSUE TITLE
Acquire a domain name

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#38]
It would be nice to have a URL where we could host things like:

* dashboard
* grafana
* blog for infra test updates
* sub-namespaces for specific teams / endeavours to post results

Keep in mind that we might want to share resources between IPFS, libp2p, and possibly even Filecoin and community projects / collaborations down the road.

**Comment by jimpick** [comment]
https://benchmarks.ipfs.team/ is currently in use as a place to publish benchmark results. (appears to be broken right now though)

**Comment by daviddias** [comment]
Why not just `testground.ipfs.team` for now? I'm able to update the DNS record, just let me know where you want me to point it at.

**Comment by jimpick** [comment]
`testground.ipfs.team` works for now, I think. 

I'm thinking we could publish a static site at that address (built on CI like our other sites).

**Comment by daviddias** [comment]
@olizilla can we haz testground.ipfs.team? We won't be using right away but want to squat it if available.

**Comment by olizilla** [comment]
yas. I was in the dns anyhoo, so `testground.ipfs.team` is now a thing.

**Comment by daviddias** [comment]
Wohooo! Thank you for being super fast. Can you make it redirect to https://github.com/ipfs/testground for the time being?

**Comment by nonsense** [comment]
testground.ipfs.team has an A record pointing to an S3 bucket, which does a redirect to https://github.com/ipfs/testground

Not sure if worth spending more effort to get the https before we actually have a proper website.

Marking this as complete for now, feel free to re-open if you think we need to do more now.
