### ISSUE TITLE
Validate a real test-case on 1K nodes

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#380]
We need to make sure:

* Sidecar doesn't fall over.
* Redis keeps up. Pay careful attention to sync service timing issues.
* We don't run into CPU contention issues.
* We don't run into weird network communication issues.

Ideally, we'd run the DHT find peer testcase. However, we may want to start with a simpler "connect everyone in a ring" test case.

**Comment by nonsense** [comment]
duplicate of https://github.com/ipfs/testground/issues/379
