### ISSUE TITLE
testplan `network/ping-pong` appears to be trying to allocate IP addresses in the wrong subnet

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#389]
Currently on `cluster_k8s.go` we have hardcoded:

```
	_, runenv.TestSubnet, err = net.ParseCIDR("10.33.10.0/24")
```

However after running multiple testplan I get the following error from `sidecar`:

```
Jan 22 13:20:07.706844  ERROR   sidecar worker failed: container worker failed: failed to update network default: failed to add network through cni plugin: unable to allocate IP address: 400 Bad Request: Unable to claim: address 10.33.1.2
/24 is already owned by ed03d2b67b07ac6e4c1e1fc06772037a3b9b1863435192f136d038828661367d
```

Looks like we are trying to claim `10.33.1.2` when in fact the test is supposed to be using `10.33.10.0/24`

**Comment by Stebalien** [comment]
Ah, yes. That test assumes we have a B block.

Note: We _need_ a B block if we want to support more than 256 nodes.

**Comment by Stebalien** [comment]
(but that test shouldn't necessarily assume that)

**Comment by nonsense** [comment]
> (but that test shouldn't necessarily assume that)

Yes, that test works only for 2 instances, not sure why it assumes we have such a large subnet :)

**Comment by Stebalien** [comment]
> Yes, that test works only for 2 instances, not sure why it assumes we have such a large subnet :)

https://github.com/ipfs/testground/blob/master/docs/NETWORKING.md#data-network

**Comment by nonsense** [comment]
OK, in this case this is a bug in the runner. Closing this.
