### ISSUE TITLE
weave is not releasing IP addresses

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#392]
It appears that Weave is not releasing IP addresses after containers are removed. This became obvious when we have only a single subnet hardcoded in the `cluster_k8s.go` runner (for example `10.33.0.0/16`).

We should investigate how to make sure that IP addresses are released to the Weave pool, even if a test fails and we force remove all its jobs/pods.

**Comment by raulk** [comment]
This could be the root cause of #396. If a previous veth is not being released, its IP address will still be held, and future veth names may collide.

**Comment by nonsense** [comment]
@raulk not sure if it is possible, but it might be the case that the `testplan` pod errors, restarts, and tries to pick up the same IP and we get `file exists`.

Basically I am not 100% sure that #396 and this issue are the same issue.

**Comment by nonsense** [comment]
We haven't had such a problem since we started using the 16.0.0.0/4 CIDR and getting a next subnet for each testplan. We might have to revisit this in the future if it comes up.

**Comment by nonsense** [comment]
@raulk I suggest we close this. We haven't had this problem since we moved away from the Job controller in K8s and since we increased the IP range for the data network. I don't think it is worth spending effort on learning in detail if there is a problem with this functionality or not, right now.
