### ISSUE TITLE
k8s nodes fail to pull image and return ImageInspectError

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#395]
This happened twice today - sometimes a host gets in this state which trying to start a container and pull its image, and doesn't seem to recover from it.

```
  Normal   Scheduled      43s               default-scheduler                                        Successfully assigned default/tg-dht-jd6ks to ip-172-20-57-254.eu-central-1.compute.internal
  Warning  InspectFailed  5s (x5 over 42s)  kubelet, ip-172-20-57-254.eu-central-1.compute.internal  Failed to inspect image "909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht:dd0841bd-3138-48b1-a0bb-67f8e43e4b64": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument
  Warning  Failed         5s (x5 over 42s)  kubelet, ip-172-20-57-254.eu-central-1.compute.internal  Error: ImageInspectError
```

**Comment by raulk** [comment]
I googled the `readlink /var/lib/docker/overlay2/l: invalid argument` error, and folks seem to suggest the image is corrupted 🤷‍♂

**Comment by nonsense** [comment]
> I googled the `readlink /var/lib/docker/overlay2/l: invalid argument` error, and folks seem to suggest the image is corrupted 🤷‍♂

Good idea. Maybe worth removing all my local caches and rebuilding everything from scratch... I do `docker system prune -f` regularly, but still...

**Comment by nonsense** [comment]
This was probably due to the number of layers I got per image - something that could happen when you are developing a Dockerfile and changing it multiple times.

I force deleted all my images, and rebuilt everything from scratch, and I haven't see this over the past few days, so will close for now.
