### ISSUE TITLE
review how weave assigns `veth` names to interfaces on `host` machines

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#396]
```
Jan 22 17:52:02.659905  ERROR   sidecar worker failed: container worker failed: failed to add network through cni plugin: could not create veth pair vethweeth1pl15c-vethweeth1pg15c: file exists       {"host": "unix:///var/run/docker.sock", "container": "15cfcbc8da80b1e900e935d788663269b91649af222c8e0e581db0527fbf6dd5"}
github.com/ipfs/testground/pkg/dockermanager.(*Manager).Manage.func3.1
        /pkg/dockermanager/dockermanager.go:135
```

When running the `dht/find-peers` testplan on k8s, I get this error from the `sidecar` - It is not clear why this `veth` pair is already existing on the host. We should probably review the algorithm with which `weave` pick up the `veth` interface names, and make sure there are no collisions on hosts.

**Comment by raulk** [comment]
Relevant snippet of code: https://github.com/weaveworks/weave/blob/7c97bb5d30bd08211cbbefab78afa8117f1c65a0/plugin/net/driver.go#L136-L139

**Comment by raulk** [comment]
Not sure where the `EndpointID` comes from. Seems from an API call. Who performs this API call? The CNI driver or sidecar?

**Comment by nonsense** [comment]
@raulk I am not sure this is the relevant snippet.

1. `sidecar` uses `libcni` package, and calls `_, err = n.cninet.AddNetworkList(ctx, netconf, rt)`, which is essentially and `ADD` command on the CNI plugin.
2. `ADD` command for `weave` CNI plugin is at `plugin/net/cni.go` -> `func (c *CNIPlugin) CmdAdd(args *skel.CmdArgs) error {`
3. From there we call `func AttachContainer(netNSPath, id, ifName, bridgeName string, mtu int, withMulticastRoute bool, cidrs []*net.IPNet, keepTXOn bool, hairpinMode bool) error {` in `net/veth.go` in the `net` package.
4. Looks like the `veth` name is generated with:
```
		name, peerName := vethPrefix+"pl"+id, vethPrefix+"pg"+id
```
5. Somewhat relevant PR on Weave side - https://github.com/weaveworks/weave/pull/3343

---

I am digging a bit deeper to understand what happened here, but I am not sure where this `Endpoint` API call is used or if at all.

**Comment by nonsense** [comment]
I think there is no problem on Weave side with respect to the veth name. This is due to a container restarting on our end I think. If we have to modify for some reason the veth names in the future, we know where that is - at the `net/veth.go` file in Weave.
