### ISSUE TITLE
fix global logger in testplans

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#399]
For some reason logs from the global logger are not visible when running `testplan --vv`, see https://github.com/ipfs/testground/pull/393/files

This is probably some misconfiguration, but it'd be good to be able to enable trace logs on testplans so that we can debug them more easily until they become stable, and until testground itself is stable.

**Comment by Stebalien** [comment]
Is this when writing to a file (`log_file`) or otherwise?

**Comment by nonsense** [comment]
Logs emitted with `logging.S().Debug` are not send to `stdout` for some reason - hence me replacing with `runenv.Message` at https://github.com/ipfs/testground/pull/393/files

I haven't tried redirecting to a file.

**Comment by Stebalien** [comment]
Hm. It looks like logging is a bit broken.

**Comment by Stebalien** [comment]
I've found two issues:

1. We use the test runner's config to set the level (`log_level`), not "-vv". Not sure what we should do here.
2. We don't set this on k8s.

**Comment by nonsense** [comment]
This has been completely revamped by Raul, so closing it.
