### ISSUE TITLE
Conceptualise GitHub automation layer

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#40]
I regard this as a mux router for GitHub webhook events. Apparently nothing like this exists (I only checked go-land).

In essence, it will be a rulebook (defined in configuration) that enumerates rules like: “on a new commit on go-ipfs/master, trigger this test plan”. Feels a bit like GitHub Actions.

Actually, at the bare minimum we should define a series of commands that befriended committers will trigger via a @testbot mention — e.g. `@testbot run <testplan> with <dependency=gitref> <dependency=gitref> <dependency=gitref>`

**Comment by raulk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Conceptualize GitHub automation layer](https://trello.com/c/gqJfnJ6W/14-conceptualize-github-automation-layer)

**Comment by daviddias** [comment]
Duplicate of https://github.com/ipfs/testground/issues/12
