### ISSUE TITLE
Testground daemon runtime

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#41]
The daemon is a long-lived server process that handles incoming GitHub webhooks, as well as explicit API calls, orchestrates test plan execution, and offers the dashboard view. It needs to model a job queue of some kind. It schedules only against nomad.

It will need a configuration file of some kind to define things like the Nomad daemon endpoint.

**Comment by daviddias** [comment]
Closing this issue, superseded by https://github.com/ipfs/testground/issues/149
