### ISSUE TITLE
k8s cluster autoscaling doesn't work

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#416]
There is a problem when autoscaling a Testground Kubernetes cluster, due to the dependencies between the various daemonsets.

1. We need to have networking daemonset installed first - `kube-flannel-ds-amd64`
2. We need to have at least one pod on the new host attached to the flannel network - done with the `dummy` daemonset.
3. Only then we can run the `weave-net` daemonset, which detects the `cni0` interface created in 2. and adds a route to DNS on every host.

---

Currently this is not working, because Kubernetes is starting every daemonset at the same time, and there are no explicit dependencies between them. We should probably address this with `initContainers` on each that wait for its dependencies, for example with: https://github.com/yogeshlonkar/pod-dependency-init-container

---

This problem is a result of https://github.com/ipfs/testground/blob/master/infra/k8s/kops-weave/weave.yml#L171 - the `initContainer` that we run prior to setting up the `weave` container. 

We need to run this `job` once on every host, and so far I've added it as an `initContainer` to `weave`, which is rather wrong, but does the trick.

This job is necessary to be run before we start `sidecar`, as `sidecar` is connecting to the host network and needs access to the cluster DNS.

Related: https://github.com/kubernetes/kubernetes/issues/64623

**Comment by nonsense** [comment]
Actually moving the `iproute` `initContainer` to `sidecar.yml` is solving most of these.

The script that the `initContainer` runs needs to be adjusted to detect if the DNS route is already present (in case we want to restart the `sidecar` daemonset).

**Comment by gmasgras** [comment]
It should also be possible to pass in `--networking flannel` into `kops create cluster` so that the flannel is automatically installed when the nodes first boot up.

**Comment by nonsense** [comment]
@gmasgras thanks for the suggestion, I completely forgot about that, and this removed 1-2 steps from the process!
