### ISSUE TITLE
Events, Zap, and Logging

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#428]
There are two PRs to log network events:

* #411 - Logs events to stderr with Zap.
* #420 - Logs events to a file manually.

Trying to reconcile these two PRs, I've realized that logging with Zap is simply _much_ more enjoyable. Zap gives us:

* `With`: We can curry fields and log with these curried fields.
* `Named`: We can have hierarchical event logs.
* Timestamps: We don't need to implement this ourselves (but absolutely _should_ timestamp all events).
* Levels: Levels let us distinguish between useful events, debug events, and errors.
* No file management: having to manage files and file lifetimes is annoying.
* A single file: this makes querying with, e.g., jq, really simple.

So I started adding an additional Zap logger for logging to a file. However, I'm having trouble drawing a line between what should be logged to the file versus what should be logged to stderr. At the moment, the only thing I can think of would be panics, but I'm starting to think those should go to stdout through the runtime.

Can someone think of where to draw the line or should we just send everything to the same place? Should we keep sending everything to stderr? Should we stop sending anything to stderr? Should we only send panics?

**Comment by Stebalien** [comment]
Related: I'd like to stop using `runenv.Message` for everything. We keep trying to shove structured data into messages. We should probably scope it down to very basic status events (i.e., "entering phase X").

**Comment by dirkmc** [comment]
For the Bitswap test plan I use `runenv.Message` for informational messages about what the test plan is doing, eg "dialing peers". I use `runenv.Metric` for outputting the actual metrics I want to collect, and I use a parseable string for the metric name so it doesn't matter about the order that things happen, for example:
```
{
  "msg":"",
  "instanceId":"e814ee3365ad",
  "eventType":"Metric",
  "elapsed":36220844400,
  "metric":
  {
    "name":"run:5/seq:4/file-size:1048576/Seed/dup_data_rcvd",
    "unit":"bytes",
    "improve_dir":-1,
    "value":0
  }
}
```
Note that this I'm still using the log_file mechanism, I haven't switched to master yet while I'm in the middle of generating data.

**Comment by hacdias** [comment]
I agree with stopping to use `runenv.Message` for everything. Also, I have a question about this issue: is it just related to the DHT plan or events/logging in general?

Either way, I agree we could stick with Zap since it provides an easy API to do what we want to do (I think).

**Comment by hacdias** [comment]
I wonder if we should block #372 until we get this decided. We might also want to use Zap.

**Comment by Stebalien** [comment]
@hacdias 

> Also, I have a question about this issue: is it just related to the DHT plan or events/logging in general?

In general.

> I wonder if we should block #372 until we get this decided. We might also want to use Zap.

Yes.

**Comment by raulk** [comment]
What are examples of using `runenv.Message()` for _everything_? Messages are human-readable informational text, they shouldn't be used for metrics. The goal is to make these messages searchable (Elasticsearch).

**Comment by raulk** [comment]
> I wonder if we should block #372 until we get this decided. We might also want to use Zap.

Nope. The runtime metrics are an _asset_, not normalised logging, which is what zap is useful for. Think of it as a file that's being dumped.

**Comment by Stebalien** [comment]
> What are examples of using runenv.Message() for everything? Messages are human-readable informational text, they shouldn't be used for metrics. The goal is to make these messages searchable (Elasticsearch).

The DHT test currently uses messages to output information like who we're dialing, our addresses, etc. My point was that we need a good place to put structured information.

> Nope. The runtime metrics are an asset, not normalised logging, which is what zap is useful for. Think of it as a file that's being dumped.

Ah, I may have misunderstood what #372 is. Don't we already have that (`runtime.EmitMetric`)?

This issue is about emitting structured events, not metrics.

**Comment by raulk** [comment]
I'm refactoring all of the logging/output/eventing. The current state is pretty spaghetti, and uneven across runners.

**Comment by raulk** [comment]
This is done!
