### ISSUE TITLE
Runner healthcheck + repair + terminate

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#432]
We want to introduce the following commands:

* `testground healthcheck [--repair] [--runner cluster:k8s]`: checks, and optionally heals, the preconditions for the runner to be able to run properly, e.g. redis, sidecar, etc.
* `testground terminate [--runner cluster:k8s]`: terminates all jobs/containers running on that runner.

Rationale:

* runners have preconditions that need to be met for tests to run successfully, e.g. redis processes/containers, sidecar, network rules, etc.
* We are moving fast, and these moving pieces will inevitably break, deadlock, spiral out of control (CPU/memory).
* We want to avoid testground developers having to deal with the internals and nitty-gritty details of the k8s setup. If things fail, they should be able to heal the cluster/setup with a single command, in an automated fashion.

Design notes for healthcheck/repair:

* A single-method interface `Healthcheckable`: `Check(repair bool) error` that runners capable of healthcheck implement.
* On starting the daemon, we should call `Healthcheck.Healthcheck(true)` on every runner.
* On performing a run, we should call `Healthcheck.Healthcheck(false)` on the runner.
* If healthchecks for a runner fail, calling `testground healthcheck --repair --runner <runner>` should attempt to fix the setup, and fail if it wasn't able to.
* Some pathological situations are not detectable via a healthcheck (e.g. sidecar deadlocks, which we know we have). Those cases will be spotted manually (i.e. the run will fail), but the user should be able to call `testground repair` to heal the situation.

Design notes for terminate:

* A single-method interface `Terminatable`: `TerminateAll() error` that runners supporting termination can implement.
* Calling such method will kill all instances (containers, processes, etc.) started by that runner.

**Comment by raulk** [comment]
@nonsense does this capture our conversation accurately?

**Comment by nonsense** [comment]
@raulk yes, sounds right to me. I would just highlight **On starting the daemon, we should call Diagnoseable.Healthcheck() on every runner.** because we don't want users to have to run yet more commands - `testground healthcheck --runner RUNNER` could be there, but users don't have to run it - it will be run automatically when starting the `testground daemon` and also when scheduling a testplan with `testground run`.

**Comment by hacdias** [comment]
Will start working on this today or tomorrow morning. Will let you know if I need any help or insights.
