### ISSUE TITLE
Proposal: unified model for test outputs

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#439]
We've had a proliferation of different PRs that all aim to bring some structure to the way we _emit_ information from a test plan.

This issue is a braindump that aims to propose a _unified model_ for test outputs, taking into account not just our short-time, immediate needs, but also the ultimate goal of testground (dashboarding, automation, etc.)

## Common vocabulary

This is not a naming war, just an attempt to establish common semantics for clarity purposes.

* Artifacts = build artifact. Let's not overload that term; "artifact" has a very specific connotation in the CI/CD world, which testground is closely related to.
* Results = normalised ndjson output that conforms to the testground schema, harvestable by the testground platform (Filebeat, Elasticsearch, Dashboard, etc.) Currently, being output on stdout.
* Assets = structured or unstructured files that a test plan consumes or emits. We have two kinds:
  * input assets: configuration files, network topology definitions, etc. made available to a test case for consumption.
  * output assets: produced by a test case during its execution. Examples include: DHT event logs, golang cpu profiles, swarm state, heap dumps, etc.

## Results

* Conformant to testground schema, which defines three event types so far: Outcome (OK, ABORT, CRASHED; needs to be revisited), Message, Metric.
* ndjson format, emitted in stdout.
* To be consumed via Filebeat, Vector, or other harvesters.
* Very useful to run a test plan manually as an executable (feeding in env variables manually), and see the results on console.
* When generating a collection zip archive (#438), results must be included as well.
  * The sidecar currently hoovers up stdout and stderr (#409), and stores on-disk.
    * for the local:docker runner, this is fine, as things are being stored on the host's disk.
    * for cluster:k8s, this design becomes problematic.
  * Unfortunately this does not work for the `local:exec` runner, which does not rely on sidecar.
  * Alternative is to use the logging framework (zap in Go) to **tee the output** to stdout and a stdout.json file, under the `TEST_ASSETS_OUT_PATH` directory.
  * I believe this simplifies things substantially, covers all runners, and removes failure points and moving parts.

## Output assets

* An output asset can be _anything_; testground doesn't care.
* Testground does not _read_ assets, it merely archives them.
* An environment variable `TEST_ASSETS_OUT_PATH` should define the location where the test plan needs to write assets, if it wants them to be harvested/collected/archived.
* The runner injects the env variable:
  * local:exec: a local directory with path, e.g. `<workdir>/assets/<plan>/<run_id>/<group_id (compositions)>/<instance_id>`.
  * local:docker: a local directory mounted as a volume.
  * cluster:k8s: an S3 bucket mounted as a volume.

## Input assets

Out of scope for now, but here are some thoughts.

* When scheduling a composition, the composition file can specify a directory to be supplied to the runner per-group, which the runner will mount as a volume (local:docker, cluster:k8s), or merely point to (local:exec), through an env variable `TEST_ASSETS_IN_PATH`.

**Comment by Stebalien** [comment]
> Assets

An asset is _always_ a shared static file (input). Artifacts (build or test) are outputs. We don't have to call them artifacts, but calling them assets is _really_ confusing.

https://stackoverflow.com/questions/25619927/what-is-the-meaning-of-artifact-in-software-testing

> The sidecar currently hoovers up stdout and stderr (#409), and stores on-disk. 
> for cluster:k8s, this design becomes problematic.

In terms of bandwidth?

> Alternative is to use the logging framework (zap in Go) to tee the output to stdout and a stdout.json file, under the TEST_ASSETS_OUT_PATH directory.
I believe this simplifies things substantially, covers all runners, and removes failure points and moving parts.

I agree.

**Comment by raulk** [comment]
This design (with a few minor digressions) was implemented in #467.
