### ISSUE TITLE
testplans to emit their ip routes after network is initialised

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#461]
Currently if a testplan fails it is hard to tell if the code under test is broken, or if there was an infrastructure failure.

It'd be nice for testplans to emit their `ip routes` as part of the testplan run under the assets dir, so that it is possible to at least confirm those were setup correctly. Then if there were any network problems due to which the test failed, we could investigate the `data` network or `redis`, etc.

Adding the `ip route` output would increase our confidence that sidecar hasn't tripped for some unknown reason, when we scale further the Testground setup.

**Comment by raulk** [comment]
This seems important and simple to do with the new `runenv.Create{Raw,Structured}Asset()` feature.

**Comment by raulk** [comment]
Rejig this issue into more general visibility into how testground is building, planning, scheduling, etc. a run.

**Comment by raulk** [comment]
It's unclear if we actually need this. If anything, I would not pollute stdout and I would export an expvar that is inspectable via pprof.
