### ISSUE TITLE
testground run requires instance number

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#475]
The commands in the USAGE doc do not work without also specifying --instance.

The usage doc suggests you can run this command:

```
> testground run single dht/find-peers \
    --builder=docker:go \
    --runner=local:docker
...
```

but this produces the following failure:

```
./testground run single  dht/find-peers --builder=docker:go  --runner=local:docker
Key: 'Composition.Global.TotalInstances' Error:Field validation for 'TotalInstances' failed on the 'required' tag
```

This same failure occurs for other plans as well.

What I would expect when --instances is not passed on the commandline that the default value from the toml manifest would be used.

**Comment by nonsense** [comment]
@coryschwartz the docs are wrong in this case - this was changed on purpose, so it is functionally correct.
