### ISSUE TITLE
Timezone needed in How We Work docs

### ISSUE THREAD

**Issue by machawk1** [ipfs/testground#481]
## Description

Missing meeting time zone in HOW_WE_WORK.md. It states "We run a Weekly Sync at 4pm Tuesdays on Zoom Room". PST, EST, GMT?

**Comment by machawk1** [comment]
It looks like @FabioMartins91 resolved this in e2da0aeaac47823fb145e093dc54724c134ca314. I would recommend linking to some means of auto-converting "6pm UTC Tuesdays" for any interested parties for clarity.

**Comment by raulk** [comment]
@machawk1 feel free to file a PR to add that link to your site of choice. Thanks!

**Comment by machawk1** [comment]
@raulk PR filed in #487.
