### ISSUE TITLE
Provide an option to replace the base docker image

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#49]
That would allow us to pull a customized docker image including additional utilities.

**Comment by raulk** [comment]
👍 Context:

* This would be a field in the `DockerGoBuilderConfig` struct, e.g. BaseImage with toml tag `base_image`.
* When empty we can default to the `golang` base image.
* Plans needing another base image can set this parameter in their manifest, under the `builder."docker:go"` toml dictionary.
* When debugging, users can override this setting with CLI flag `-run-cfg base_image=foo`.

**Comment by jimpick** [comment]
I could probably use with with #74 ... I don't want to merge it with it's current modifications to Dockerfile.template.

**Comment by daviddias** [comment]
From the perspective of a Test Plan writer, not being able to specify a Dockerfile is a bug. ref: https://github.com/ipfs/testground/issues/224

**Comment by raulk** [comment]
This issue is still valid.

**Comment by raulk** [comment]
Instead of doing this, we will provide a generic Docker builder, such that test plans can supply their own Dockerfile: https://github.com/ipfs/testground/issues/692.
