### ISSUE TITLE
Running many tests together

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/testground#500]
There is not currently any tooling around running many tests (same artifacts different parameters).

I suspect that many of the DHT tests will take a long time to run. Therefore, being able to run a whole suite of tests overnight or for a few hours while the developer is otherwise occupied would be great.

This could be as high level as having a TOML file that deals with ranges/arrays, or as low level as a script that generates a set of TOML files combined with a script that runs them all.

**Comment by dirkmc** [comment]
For the bitswap tests I worked around this by being able to pass a run_count parameter and an array of filesizes so I could run several iterations of a test against several file sizes that I was transferring:
https://github.com/ipfs/testground/pull/345

**Comment by raulk** [comment]
Tracking this in the matrix parameters issue: #519. Thanks for the feedback, @dirkmc. Likely to land in testground v0.3.
