### ISSUE TITLE
have writer implement io.Writer

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#508]
I find myself wishing to use the writer with something like something like the io.Writer api, without the requirement for the subtree structure for each request.

If there were an object I could treat like a Writer, already configured to use the right subtree, I suspect this would be familiar and usable.

**Comment by raulk** [comment]
@coryschwartz The Sync API `Write()` operation is more akin to a `Publish()` than to a standard IO write. You will probably only write one piece of data, once, i.e. not a stream. IMO implementing this won't prove very useful. If the `Write()` method name is what's confusing, we could consider renaming that to `Publish()` or something else.

If you feel strongly about the latter, feel free to open a new issue so we can discuss that solution. For now, I'll just close this issue.
