### ISSUE TITLE
Spike: investigate how to build test plans that stay compatible with breaking upstream API changes

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#524]
"Ingredients" we've discussed to make this work:

* shimming on the side of the test plan.
* shimming on the side of the evolving component.
* build tags, e.g. the builder can inject a gazillion build tags representing upstream dependency versions, such that test plans can then adequately select which shim to build.
* interface assertions (does not work with new/removed types).
* reflection (ugh)

**Comment by Stebalien** [comment]
The only general solution I can see is to allow each composition group to specify a builder and the inputs to that builder (e.g., which test instance to load). Specifically, `groups.build.builder = ...` and `groups.build.source_path = ...`. That's the only one that'll allow, e.g., other languages.

However, for now, a simple build script would be enough. We could even just have one that:

1. Depends on all the deps it cares about.
2. Uses type assertions to do feature detection.
3. Prints the relevant build tags to stdout.

**Comment by raulk** [comment]
DRI @raulk.

**Comment by raulk** [comment]
Spec written, and manual build selectors implemented in #566.
