### ISSUE TITLE
testground outputs hardening (performance/reliability)

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#538]
Right now if there is a failure during startup on the `s3bucket`, it is easy for it to end up in `CrashLoopBackoff`, since directories exist on the host, and it can't mount an S3 bucket on them again.

We should fix this - one solution might be to add an `initContainer` that makes sure that directories do not exist, prior to `s3fs` starting.

---

Basically the acceptance criteria here is that s3bucket should be restartable, and I am pretty sure this is not the case now.

**Comment by nonsense** [comment]
s3fs is not very reliable. We should probably rethink how we are solving the problem of shipping logs to s3 - either doing it at the end of the testplan run, or using AWS EFS, or some other solution.

**Comment by raulk** [comment]
@nonsense 

* Looks like @jimpick has experience with AWS EFS, and might be able to assist.
* Are we able to ship the S3 => EFS migration for v0.2 (if we stretch the end date to Mon/Tue)?

**Comment by nonsense** [comment]
> Are we able to ship the S3 => EFS migration for v0.2 (if we stretch the end date to Mon/Tue)?

I could have a look into this next, most probably on Monday. We could try to get it in for Tue, if things work out nicely.

**Comment by Robmat05** [comment]
This has been marked as ‘Closed’ by Anton. I am forwarding it to review to confirm functionality and will move to respective pipeline depending on review.

**Comment by raulk** [comment]
This was closed in #596.
