### ISSUE TITLE
Collecting assets from S3 is unbearably slow

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#542]
According to @nonsense, it takes 2 minutes. According to @aschmahmann, it was taking over an hour (transatlantic).

At a minimum, we should parallelize the requests inside the daemon, buffering the results in-memory. We already know the correct sizes for these results so we can even detect large assets and stream those to avoid using too much memory.

**Comment by Stebalien** [comment]
I know @aschmahmann was looking into this.

**Comment by nonsense** [comment]
@Stebalien there are two problems that we uncovered through @aschmahmann 's testing:
1. Region selection matters a lot depending on connection:
EU -> EU: 10 second download for 2k files (my ISP) via `aws s3 cp --recursive`
EU -> US: 30 second download for 2k files (my ISP) via `aws s3 cp --recursive`
US -> EU: very many seconds download for 2k files (@aschmahmann ISP) via `aws s3 cp --recursive`
US -> US: 10 second download for 2k files (@aschmahmann ISP) via `aws s3 cp --recursive`

We uncovered a few things that had to be fixed so that `region` is fully configurable in our setup, and that's mostly done now.

2. As commented on the PR, our implementation of `testground collect` is slow, due to the sequential download due to the in-memory archiving. We should probably rethink this.

**Comment by nonsense** [comment]
As a short term fix we could just skip the archiving (folks are actually unarchiving the archive as soon as it lands on their machines), and just invoke `aws s3 cp --recursive` from `testground collect`.

WDYT ?

**Comment by Stebalien** [comment]
> As a short term fix we could just skip the archiving (folks are actually extracting the archive as soon as it lands on their machines), and just invoke aws s3 cp --recursive from testground collect.

How would we do this? We need to ship the results back to the user over the HTTP API from the daemon.

We could just recursively fetch the results into a local directory then ship _that_ to the user.

**Comment by nonsense** [comment]
> We could just recursively fetch the results into a local directory then ship that to the user.

Yes, we could do that.

> How would we do this? We need to ship the results back to the user over the HTTP API from the daemon.

I was thinking on just doing this from the client (both client and daemon live on the developers machine right now) we are not running in server-client mode, and we can push this problem into the future, when we have more information on the usage pattern.

**Comment by Stebalien** [comment]
> I was thinking on just doing this from the client (both client and daemon live on the developers machine right now) we are not running in server-client mode, and we can push this problem into the future, when we have more information on the usage pattern.

I'd rather not do that. That's going to clutter the client with runner-specific logic.

**Comment by raulk** [comment]
Can the daemon download the files recursively to workdir (available in EnvConfig), and then zip them before streaming the response back to the client?

**Comment by nonsense** [comment]
> Can the daemon download the files recursively to workdir (available in EnvConfig), and then zip them before streaming the response back to the client?

Yes, this is what I will be doing. I was thinking of downloading in a temp dir though, not in a workdir, but these are details.

**Comment by raulk** [comment]
You can create a temp dir inside the workdir, that way we don’t scatter temporary files around the filesystem. (That’s what the builders do.)

**Comment by nonsense** [comment]
> You can create a temp dir inside the workdir, that way we don’t scatter temporary files around the filesystem. (That’s what the builders do.)

But then you are responsible for cleaning it up yourself, otherwise the OS takes care of that on reboot :)

**Comment by nonsense** [comment]
Fixed as part of https://github.com/ipfs/testground/pull/596 . Would be happy to hear some feedback from users - cc @Stebalien @aschmahmann @dirkmc  ( I know you mostly use the local adapters, but still).

**Comment by Robmat05** [comment]
Per the above, and given no feedback.  I am closing this ticket as resolved. Feel free to reach out to me in order to re-open if necessary.
