### ISSUE TITLE
Collect and push Prometheus metrics via pushgateway

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#544]
* Various libraries/projects that testground caters to export Prometheus metrics (IPFS and libp2p); in the future they'll use OpenCensus/OpenTelemetry/whatever the new kid on the block is, but whatever it is, it'll have a Prom exporter.
* We want to collect snapshots of go runtime metrics (#372). [The Go Prometheus client already exports these for us for free.](https://prometheus.io/docs/guides/go-application/)
* We want these metrics to be available for both live monitoring and as assets (periodic snapshots), so they are part of the output bundle.
* Given that our workloads are ephemeral, we cannot default to Prometheus scraping, as the instance may have finished by the time it gets scraped.
* We therefore need to use the Prometheus push functionality, along with a PushGateway.

This task includes the following:

- [x] Deploy a [PushGateway helm chart](https://github.com/helm/charts/tree/master/stable/prometheus-pushgateway/) on k8s.
- [x] Make sure the push gateway is connected to the control network.
- [x] Make sure the push gateway is accessible via DNS.
- [x] Make sure that Prometheus introduced in https://github.com/ipfs/testground/pull/534 is scraping the push gateway(s).

**Comment by coryschwartz** [comment]
added in https://github.com/ipfs/testground/pull/564

**Comment by raulk** [comment]
This was implemented in #564 and follow-ups.
