### ISSUE TITLE
cni plugin: attaching veth "vl0e4d4de7457ac" to "weave": exchange full

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#549]
```
Feb 13 11:30:07.313745  ERROR   sidecar worker failed: container worker failed: failed to add network through cni plugin: attaching veth "vl0e4d4de7457ac" to "weave": exchange full     {"host": "unix:///var/run/docker.sock", "container": "0e4d4de7457ac8d197218d7c26551949b307daac8f6081b88459c06a75982652"} github.com/ipfs/testground/pkg/dockermanager.(*Manager).Manage.func3.1
        /pkg/dockermanager/dockermanager.go:168
```

Related:

1. https://github.com/weaveworks/weave/issues/3406
2. https://github.com/weaveworks/weave/issues/3258

**Comment by raulk** [comment]
How often does this happen?

**Comment by nonsense** [comment]
@aschmahmann reported it once, but we couldn't debug as we didn't have the cluster setup with a shared key.

**Comment by nonsense** [comment]
@raulk there are reports of this happening on Weave as well, now that we have the shared clusters capability, if it happens again, I can log in to @aschmahmann cluster and try to understand what's going on - this would have been very difficult if we have to screen-share and pair with @aschmahmann specially while he has to focus on other tasks.

---

Will report back when we have more information on it, but I assume we will be able to reproduce again on a cluster of 15-20 machines, after running 1k instance testplans multiple times.

**Comment by nonsense** [comment]
This is probably a problem on `sidecar` side - we have a `start` event, which calls `Manage` and we add the `data` network.

However we don't really do anything on a `stop` event, we should probably be calling the CNI delete command to clean up the Weave interface - I was under the impression that this happens automatically, but this is not the case.
