### ISSUE TITLE
AWS Tags

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#55]
If you are creating virtual machines or other resources on AWS, please add some tags so we can track costs ... **anything that isn't tagged will be deleted** (if we can't figure out what it's being used for)

Edit the table below to add tags:

| Tag Key   | Tag Value           | Contact       | Description                                  | Keep until date     |
| --------- | ---------------- | ----------- | ------------------------------- | ----------------- | 
| Project     | Jim_Testground | @jimpick      | Experimenting with Testground | 2019.10.25            | 
| Project     | Packer                | @jimpick      | Building images | 2019.10.25            |

**Comment by daviddias** [comment]
@jimpick mind adding this to the docs of the project as well?

**Comment by daviddias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up AWS infrastructure (docker-machine -d aws)](https://trello.com/c/9uvG4oTv/30-set-up-aws-infrastructure-docker-machine-d-aws)

**Comment by jimpick** [comment]
I can do that, but I'm wondering if we should keep the code for the testground framework separated from the big messy repo where we discuss what to test and the specifics of our in-house deployment?

**Comment by jimpick** [comment]
The terraform scripts apply a 'TG' tag for each cluster when creating it, so mostly everything is tagged in AWS. Eventually, we should probably track these somewhere ... for now, I think it's OK if we don't track it super closely, especially if we do autoscaling where the clusters scale the workers down to zero when not in use - so I'm going to close this issue.
