### ISSUE TITLE
add functionality for multiple people to access the same k8s cluster

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#550]
1. We need to be able to have multiple people access the same k8s cluster.
2. We need to have full root access to all hosts on the given k8s cluster.

**Comment by raulk** [comment]
Access as in...? Schedule jobs or SSH into it for debugging?

**Comment by nonsense** [comment]
Access to kubernetes context, so full control of the kubernetes API.

And access to host as in root ssh, so we can inspect kubelet logs and other relevant logs. 

The PR is already accounting for both of these.

**Comment by nonsense** [comment]
@raulk this is for debug purposes, not for developers sharing clusters.

**Comment by raulk** [comment]
Gotcha! SGTM
