### ISSUE TITLE
smlbench tests do not run

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#56]
I was looking through the code of the smlbench tests to use it as a reference for Test Case 1. They don't run at the moment and it is easy to understand why. The manifest is a c&p from the DHT tests one.

Should I take any inspiration at all from these tests? It seems that the way that is being used to spawn a go-ipfs daemon is by running a wired version of IPTB, programmatically. Is this intended? Still the plan or should we look into spawning a go-ipfs daemon and using the go-ipfs-api to operate it.

**Comment by jimpick** [comment]
I think that code is from several weeks ago and quite a bit changed ... really only one test is working at the moment.

**Comment by daviddias** [comment]
This has been fixed with https://github.com/ipfs/testground/pull/60
