### ISSUE TITLE
upgrade Kubernetes to 1.17 in cluster.yaml

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#594]
Prior to https://github.com/ipfs/testground/pull/534 we were running Kubernetes 1.17, and now we are on 1.15.9 (see `cluster.yaml`)

It would probably be a good idea to upgrade to the most recent version of Kubernetes in order to not encounter bugs that are solved between 1.15 and 1.17.

**Comment by coryschwartz** [comment]
This is ready to be closed.

**Comment by Robmat05** [comment]
This was rolled back. It will slide into sprint v0.4 and will be either re-examined or a new ticket will be created to resolve issue.

**Comment by coryschwartz** [comment]
The helm chart for prometheus operator isn't ready for helm3, It uses CRD hooks. 

https://github.com/argoproj/argo-helm/issues/169
https://github.com/helm/charts/issues/17511

I can use helm v2, but that's not what we use for the rest of the installs, so I'd prefer to stick to helm 3

I'll have a review tomorrow.
