### ISSUE TITLE
Publish metrics from plans

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#598]
Some way of pushing metrics from plans, so they can be visualized:

- [ ] Maybe RecordMetric can save metrics into our metrics system

- [ ] Maybe we use OpenSensus in the RecordMetric logic

- [ ] Maybe we expose OpenCensus, OpenTelemetry, etc. directly into the plan

**Comment by raulk** [comment]
This was accomplished by setting up Prometheus, adding a metrics API to create gauges, histograms, summaries, counters from the runenv, and working with Pushgateway to push metrics to Prometheus proactively.
