### ISSUE TITLE
increase visibility into redis

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#620]
Redis has been one of the dependencies that we've had lack of visibility over the last 1-2 months when running testplans.

We are already working on adding metrics collection and visualisations from the perspective of testplans in other issues.

It'd be nice if we add monitoring to Redis as well - something similar to https://github.com/oliver006/redis_exporter would be a good start I think.

WDYT?

cc @coryschwartz @raulk

**Comment by coryschwartz** [comment]
We have the redis exporter on k8s and local docker (and soon on local exec runner also) so I think this can be closed.
