### ISSUE TITLE
Ensure test plans can be imported from other Git repos

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#629]
We use go-getter, so this theoretically should work out of the box. But let's test it.

Filecoin (go-lotus) needs this.

**Comment by nonsense** [comment]
@raulk , yes specifying a `git` repo works out of the box, for example in `manifests/network.toml`:

```
source_path = "git://github.com/nonsense/network-ping-pong"
```

I am considering how to improve these altogether:

1. support importing of test plans from other Git repos ; issue #629
2. document creation and update mechanics for a new testplan ; issue #609
3. move build/image push to the k8s cluster ; issue #572 (faster build/run feedback loop, when working in env with slow internet connection)
