### ISSUE TITLE
create sample intuitive dashboards for counters and timers

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#633]
At the moment it is not documented how a developer should add measurements to their testplans with the Testground SDK and then visualise them in Grafana. For example adding a counter and then visualising in Grafana and Prometheus Web UI might result in:

1. 
<img width="1609" alt="Screenshot 2020-03-02 at 11 30 29" src="https://user-images.githubusercontent.com/50459/75876681-7137df80-5e16-11ea-9596-d7b5381b45e0.png">

2.
<img width="1655" alt="Screenshot 2020-03-02 at 11 34 28" src="https://user-images.githubusercontent.com/50459/75876707-79901a80-5e16-11ea-90dd-8caeb0684fac.png">

---

We need to document how the scrape intervals are configured, and add explanations on the various scrape intervals that affect resolution in the visualisation tools.

Note that the screenshot from Grafana from above (1.) is not intuitive - it shows that the rate of change in the counter is 30 for 30sec. which is incorrect if you look into the code (https://github.com/ipfs/testground/pull/616). actually we increment the counter every 2 seconds, so we have a change of 30 for 60sec. not 30sec.

This is due to the other interval added to the dashboard, which currently doesn't appear to be changeable - `[1m]`.

**Comment by Robmat05** [comment]
Was in progress by Anton. Re-assigning to @coryschwartz to finish in this sprint

**Comment by coryschwartz** [comment]
I have added sample dashboards, the redis dash, and the dashboard for benchmarks. All could be improved, for sure, but they are there now.

**Comment by Robmat05** [comment]
Nice job, way to kick some serious ass, yesterday!
