### ISSUE TITLE
add weave monitoring

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#634]

**Comment by coryschwartz** [comment]
I'll take a crack at this.

**Comment by alok87** [comment]
@coryschwartz This can help https://github.com/weaveworks/weave/pull/3780

**Comment by coryschwartz** [comment]
I'll have a look at this tomorrow. Thanks for the pointer @alok87!

**Comment by coryschwartz** [comment]
I want to do a *bit* more testing, and add the dashboard before closing this ticket
