### ISSUE TITLE
regression: prometheus operator fails to start

### ISSUE THREAD

**Issue by coryschwartz** [ipfs/testground#656]
After upgrading the kubernetes version in https://github.com/ipfs/testground/pull/650
I failed to realize before merging that the upgraded kubernetes depreciated api versions still utilized by the prometheus-operator kops addon.

https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis

I have created an issue with kops, but I suspect there is more luck to be had by moving the installation procedure from kops addon to a helm chart.

**Comment by Robmat05** [comment]
Added to sprint as P1 Bug

**Comment by coryschwartz** [comment]
The weave service monitor (the way it is installed now) also fails. It fails because the CRD isn't available until the operator is added. Besides it looks like I need to add some more permissions, I am seeing things not being registered as 'up', and I need to have a harder look at this. I'm going to revert, for now and try this again later.

**Comment by coryschwartz** [comment]
Closing since reverted, and https://github.com/ipfs/testground/issues/650 is now re-opened.
