### ISSUE TITLE
`cluster:k8s`: Leftovers from S3 => EFS migration

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#668]
@coryschwartz -- please replace this placeholder with a checklist.

---

Spun off from https://github.com/ipfs/testground/pull/596.

**Comment by raulk** [comment]
@Robmat05 -- FYI.

**Comment by Robmat05** [comment]
Given it’s priority with other teams, I am moving this up to the top of the backlog so as to prioritize it for the v0.4 sprint plan discussion

**Comment by coryschwartz** [comment]
@raulk 

There is another ticket which deals with the runner initialization https://github.com/ipfs/testground/issues/680

The other bit of cleanup is the Fixes logic.  Is there anything else you would include here?

**Comment by raulk** [comment]
SGTM. We can close this. I opened this as a placeholder because you mentioned there were follow-ups, but it seems that those are addressed already! ;-)
