### ISSUE TITLE
ElasticSearch deployment alternatives

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#67]
There are many, many different options for deploying an ElasticSearch cluster...

Right now, we're using the "Elastic Cloud" offering from Elastic, for ease-of-setup + unified billing (via AWS Marketplace) + it's got the latest features and matches the online documentation. However, it's not open source ... here's the full feature matrix:

https://www.elastic.co/subscriptions (click on "Expand all features")

The "Elastic Cloud" version automates a lot of the tasks involved in running a cluster, but it's not fully managed - there are still admin tasks that somebody will have to perform.

The open source version probably gives us most of what we need for Filebeat/ElasticSearch (needs to be confirmed) ... the Elastic Cloud version of Kibana has a lot of features that aren't in the Open Source version.

"Elastic Cloud" can be purchased directly from Elastic.co or via the AWS Marketplace. If purchased direct, it can be deployed on either AWS or GCP. If purchased via AWS Marketplace, only AWS is available (no surprise) ... the nice thing is that the billing is integrated into the AWS bill. I'm only provisioning a tiny install so far, so I haven't evaluated costs - it's billed hourly on AWS Marketplace based on the size and number of servers used in the cluster.

The Open Source version of the Elastic Stack can be set up manually, and is available in many Linux distributions. Setting up a cluster is a fair amount of effort though. If the volume of data we need to store gets really large, it might be more economical to go this route.

AWS has a competing hosted ElasticSearch offering: https://aws.amazon.com/elasticsearch-service/ ... and is sponsoring an alternative open source distribution to the Elastic.co commercial version: https://opendistro.github.io/for-elasticsearch/

There are also other paid hosted services, eg. https://logz.io/

**Comment by jimpick** [comment]
Saw this on HN:

* https://spun.io/2019/10/10/aws-elasticsearch-a-fundamentally-flawed-offering/
* https://news.ycombinator.com/item?id=21227479

**Comment by daviddias** [comment]
Are there next steps to this thread?

**Comment by jimpick** [comment]
At the time, this was mostly an informational issue about what I had done/decided so that people would have the opportunity to point me in a different direction if they wanted ... the hosted ElasticSearch option chosen seems to have been OK for the short term. I'll close this. @nonsense or @raulk can start a new issue if they'd like to explore different options.
