### ISSUE TITLE
Check if prometheus-pushgateway is alive before scheduling periodic push

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#685]
To solve https://github.com/ipfs/testground/issues/637, and in complement to https://github.com/ipfs/testground/issues/660, we should check if the pushgateway is alive in any of the expected addresses, by sending an HTTP GET request to trigger the `status` operation. See https://github.com/prometheus/pushgateway#query-api

We can then check if the status is `success`, and only enable the periodic push in that case, with the endpoint that tested positive.

The expected endpoints are:

* `prometheus-pushgateway:9091` (`local:docker`, `cluster:k8s`).
* `localhost:9091` (`local:exec`), which could be backed by a Docker container with published ports.

**Comment by Robmat05** [comment]
@coryschwartz This is an issue not a pr so does not need review/merge. If this done, then close it, if you only have questions, then pose them here and we can decide if this close it or slide it to the next sprint
