### ISSUE TITLE
DRY-er healthchecks and fixes code

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#720]
Let's find a sane way of creating an API to remove all the repetitiveness / duplication in Healthchecks and make them DRY.

- [ ] A healthcheck runner that condenses the logic of performing checks serially, and storing their results.
- [ ] A set of helpers for common healthchecks (e.g. does container exist, does network exist).

## Potential healthcheck runner API

```go
var hh HealthcheckHelper

// first closure is the checker, second is the fixer
hh.Enlist("control-network", func(), func())
hh.Enlist("sidecar-container", func(), func())
hh.Enlist("pushgateway-container", func(), func())

checks, tofix := hh.RunChecks() // will remember which healthchecks failed
if tofix && fix {
    hh.RunFixes()
}
```

**Comment by coryschwartz** [comment]
Definitely need this.

The way I added to the local:exec runner https://github.com/ipfs/testground/pull/703 is half way there for that runner,
