### ISSUE TITLE
Scaling Redis on `local:docker` and `cluster:k8s` runners

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#727]
A few of us just had a Redis scaling session! Conclusions:

- We ran benchmarks successfully up to 80k connections. Redis did not flinch, when configured properly. I ❤️ Redis. Latest battle-tested Redis config, complemented by disabling Transparent Huge Pages:

```
docker run --network test-network --name "testground-redis2"  --sysctl "net.core.somaxconn=150000" --ulimit "nofile=1048576:1048576" --sysctl "net.netfilter.nf_conntrack_max=120000" redis --appendonly no --maxclients 120000
```

- GET, SET, INCR benchmarks with 80k concurrent clients, with benchmarks highly contending for CPU (my docker VM has 4 cores, and we were at 100% global usage) was around 1.2-1.5s avg depending on operation.
    - Redis CPU usage was zen, ~13% tops under that load. This is not only acceptable for Testground, but it’s amazing.
    - These are the primitives we use for barriers, so we’re pretty certain that barriers will scale pretty well.
- Redis does not ship with Stream benchmarks (XREAD, XADD), so not quick way to get an assessment of those primitives under stress/load. They are used for subtree subscriptions.
    - Based on what I’ve seen of Redis, I do not think Redis will hold us back here.
    - I suspect that how test plans use the data is what might be killing us.
    - If we accumulate all entries received in a subscription in memory (e.g. peer IDs, multiaddrs, etc.), and all test instances do this, globally we are incurring in a usage of O(m^n) memory, where m is the payload size, and n is the number of participating instances.

## Action items

- [x] @nonsense to tackle applying the scaling settings to cluster:k8s.
- [x] @raulk to do the analogous for local:docker.
- [x] @raulk to instrument the sync service with Prometheus metrics (per-barrier, per-subtree summaries).

**Comment by raulk** [comment]
Running benchmarks. We ran 4 of these to generate 80000 parallel clients.

```
docker run --network test-network --name "redis-bench-3"  --sysctl "net.core.somaxconn=65535" --ulimit "nofile=1048576:1048576" redis redis-benchmark -c 20000 -h 172.19.0.2 -d 512 -P 16 -r 10000 -t SET,GET,INCR
```

**Comment by coryschwartz** [comment]
They do discuss disabling THP on https://redis.io/topics/latency but I am still shocked that there is such a massive difference. Good to hear this is so much better now!
