### ISSUE TITLE
make the daemon a building/running engine with no knowledge of test plans

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#747]
@nonsense ran ahead and already filed a WIP PR for this: #735 🎉🎉🎉 But here's the formal description of what we want to do.

We want to achieve the following:

1. - [x] Stop loading manifests and test plans at the daemon side.
    * - [x] The daemon should have no knowledge of manifests or test plans.
    * - [x] These are purely human/machine readable descriptions so that users know what test cases are within a given test plan, and which parameters each accepts.
2. - [x] The client should submit the full source of the test plan it wants to build/run.
3. - [x] Build and run submissions should be a multipart `POST` request.
    * - [x] composition file (application/text?).
    * - [x] tar.gz file of the source (with optionally the sdk, see below).
4. - [x] _By default,_ builders stop doing the sdk replaces.
   * - [x] This was a very useful feature for early development of Testground, where we were changing the SDK very rapidly.
   * - [x] We should use the sdk version specified in the test plan's go.mod.
   * - [x] Users can enable the sdk replaces through a CLI flag `--sdk-replace=<directory>`
   * - [x] Doing so would ship a third part in the multipart request with the sdk source.
   * - [x] Only then would the daemon apply the sdk replaces.

**Notes:**
1. At some point, we'll need to worry about GCing build artifacts (docker and exec).
2. Docker caching will still work, since the hash of the original image (built with the incoming tar) should be preserved across builds.
3. I think that Golang build caches will also be in effect, even if we deflate and untar the incoming source in a random temp directory each time.
   * Seemingly the caches are hash-based: https://golang.org/cmd/go/#hdr-Build_and_test_caching
   * But we should verify this with our own eyes.

**Comment by Robmat05** [comment]
IN process and on-time for sprint close
