### ISSUE TITLE
ulimit nofile (-n) of test instances should be 1Mi by default on local:docker and cluster:k8s

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#781]
## Context

Some downstreams like the _hardening gossipsub_ initiative are looking to run many libp2p nodes inside a single test instance as a way to optimise resources. ulimits are standing in the way.

## Solution

* Crank up the default ulimit nofile to 1Mi.
* Add a config param to both runners: Ulimit, that accepts a Docker-formatted ulimit string, and parses it with https://godoc.org/github.com/docker/go-units#ParseUlimit.
    * See https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit for more info.
* The default value should be a string const on each runner: `nofile=1048576:1048576`.

**Comment by coryschwartz** [comment]
Maybe this isn't so easy on kubernetes, at least through the API: https://github.com/kubernetes/kubernetes/issues/3595


But we control the host deployment through kops, so I think we can modify this with our kops config.

**Comment by coryschwartz** [comment]
@Robmat05 This is implemented by the two referenced PRs, and can be closed as son as those are.

**Comment by coryschwartz** [comment]
It's unclear to me what the underlying issue was which motivated this ticket. I can verify that the ulimits are configured by the two PRs, but I can't confirm whether this fixes the original problem, if there is a specific branch or plan to test against.

**Comment by raulk** [comment]
@coryschwartz confirming that the ulimits are being applied is sufficient, thanks.

**Comment by raulk** [comment]
Closed in #784.
