### ISSUE TITLE
Using testground to test Bitswap in varying leech / seed combinations

### ISSUE THREAD

**Issue by dirkmc** [ipfs/testground#79]
There are a couple of test plans for testing Bitswap performance:
- https://github.com/ipfs/testground/tree/master/plans/data-transfer-datasets-random
- https://github.com/ipfs/testground/tree/master/plans/data-transfer-datasets-interest

These are good real-world tests that can be used to determine if a change to Bitswap is safe to release.

As mentioned in the above test plans, for Bitswap we are most concerned about
- overall transfer time
- overall data transfer (ie how much unique vs duplicate data is transferred)

It would be helpful to also run more focused tests that isolate the effect of changes, in particular to benchmark each combination of L leeches pulling from S seeds:
- 1 leech pulling from
  - 1 seed
  - 2 seeds
  - 4 seeds
  - 8 seeds
  - 16 seeds
- 2 leeches pulling from
  - 1 seed
  - 2 seeds
  - 4 seeds
  - 8 seeds
  - 16 seeds
- 4 leeches ...
- 8 leeches ...
- 16 leeches ...

For these tests we would not be concerned with connection management - all nodes would be connected directly to each other.

**Comment by daviddias** [comment]
@dirkmc thanks for creating these notes and reviewing the Test Plans focused on data exchange! 

I like the direction you are headed and seems that it would be worth to have a Test Plan focused on all Bitswap specifics. Would you like to kick off the specs and/or own it?

**Comment by dirkmc** [comment]
Sure, I'm happy to do so - by kick off the specs do you mean I should create a PR for a test plan in the `plans` directory?

**Comment by jimpick** [comment]
I'm trying to imagine what a top-level configuration for the tests might look like.

eg. if we used a [TOML array of tables](https://github.com/toml-lang/toml#array-of-tables
), similar to what is used in the Testground test manifests, it could look something like:

```
[[tests]]
leeches = 1
seeds = 1
[[tests]]
leeches = 1
seeds = 2
[[tests]]
leeches = 1
seeds = 2

... etc
```

We could use something like JSON or YAML instead. We could go with something more compact with YAML and tuples instead, eg.

```
tests:
- [1, 1]
- [1, 2]
- [1, 3]
```

We could also parameterize things like the generated file size, and any bandwidth throttling parameters.

There currently isn't any support in testground for iterating over things at the top-level yet, so we'd have to implement that. Maybe @raulk has some ideas in mind for how to organize this type of test?

**Comment by daviddias** [comment]
@dirkmc exactly :)

**Comment by jimpick** [comment]
Another easy option is to not worry about having a top-level configuration just yet and just use a shell script to call the testground binary repeatedly with different parameters.

**Comment by jimpick** [comment]
For setting up the seeds, there are a couple of ways we could do that:

* generate a random file, transfer it to all the seed peers (how? http maybe?), and `ipfs add` it on each
* generate a random file, `ipfs add` it on a single seed peer, use `ipfs get` on all the other seed peers to get it
* generate a random file and put it on an EBS snapshot, and mount it on the seed peers (probably overkill for this test, but useful for large dataset testing)

We can probably get the test working for 1 seed peer trivially, and then add support after for more than 1 seed peer.

**Comment by dirkmc** [comment]
Seems like we should probably use IPFS to transfer files 😄 
p2plab does this and it works great

**Comment by raulk** [comment]
Hey, my thoughts on how I'd go about building this.

I'd create a single parametrisable test case with two variables: `num_seeds`, `file_size`. The total number of instances is passed when running the test case, mapped to `TEST_INSTANCE_COUNT`, and populated in the `RunEnv` object.

The test logic would do the following. It's pretty simple.

1. Use the sync service to publish the peer subtree. This operation returns the `seq` of the current instance enrolled in the distributed context of the test case.
2. If `seq <= NUM_SEEDS`, we're a seed. Use a pseudo-random generator to generate a file of size `file_size`. Add it to IPFS. Write the CID on the sync tree, and signal entry into the `SEED_READY` state (non-blocking). Await/block until the number of nodes in the `LEECH_DONE` state == the number of leeches.
3. If `seq > NUM_SEEDS`, we're a leech. Wait/block until the number of nodes in the `SEED_READY` state == number of seeds. All seeds are ready now. Read seed peer multiaddrs from the peer subtree, and connect to them. Read from the CID subtree, and fetch the file. When done, signal entry into `LEECH_DONE` state.
4. All seeds record the time taken to retrieve the file, although I think to make this more useful we need more granular per-operation statistics in Bitswap.

**Comment by jimpick** [comment]
@raulk Sounds pretty close to what's in implemented in https://github.com/ipfs/testground/pull/74 (for the single seed situation)

For multiple seeds, are you suggesting that we should have a different random file on each seed? I had assumed that we'd want the same file on each seed.

**Comment by dirkmc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Plan Spec focused on Bitswap testing](https://trello.com/c/1meup3sM/72-create-plan-spec-focused-on-bitswap-testing)

**Comment by daviddias** [comment]
Main work track issue https://github.com/ipfs/testground/issues/100
