### ISSUE TITLE
Review: Chewing strategies for Large DataSets

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#80]
see: https://github.com/ipfs/testground/blob/02ec37ecee35c5ccd62911eea19a8f275b2903f0/plans/chew-large-datasets/README.md

# Test Parameters

* The directory depths allow specifying file sizes but file sizes can _also_ be specified independently. How are these resolved?
* As far as I can tell, one currently needs to explicitly list out every file to be added in `File Sizes`. Instead, we should have a list of `[{average: ..., variance: ..., percent: ...}]` and a final total file count (where the `percent` fields add to 100%). Otherwise, generating realistic tests will be really tedious.

For example:

```
{
  depth: 4,
  numFiles: 1e6, // maybe allow a list and test with each one?
  fileSizes: [
    {average: "1MiB", variance: "10%", percent: "90%"},
    {average: "1KiB", variance: "0%", percent: "10%"},
  ]
}
```

# [IPFS MFS Write](https://github.com/ipfs/testground/blob/02ec37ecee35c5ccd62911eea19a8f275b2903f0/plans/chew-large-datasets/README.md#test--ipfs-mfs-write)

>     - Pin the MFS root hash

The MFS root hash is _always_ pinned (in go-ipfs).

# [IPFS Url Store / IPFS File Store](https://github.com/ipfs/testground/blob/02ec37ecee35c5ccd62911eea19a8f275b2903f0/plans/chew-large-datasets/README.md#test-ipfs-url-store)

To be explicit:

* `Run FileStore` doesn't _really_ make sense. I assume you meant: add the files using the filestore  (e.g., `ipfs add --nocopy`).
* Verifying that all the files are listed involves running `ipfs filestore ls` to list all blocks and their filenames/urls.

**Comment by daviddias** [comment]
Ack. Thanks for the review @Stebalien! 

For the next one, if it is simpler for you, try to do the PR to the spec directly. For this one, I'll apply it myself.

**Comment by daviddias** [comment]
Continue at https://github.com/ipfs/testground/pull/81

**Comment by daviddias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Plan spec focused on Bitswap testing](https://trello.com/c/1meup3sM/72-create-plan-spec-focused-on-bitswap-testing)

**Comment by daviddias** [comment]
Applied most of the feedback with #81 

Just missing the point on Test Parameters. Need to think a bit more about how to land that (if the format suggest is the right one or if it should be another one). The bit of feedback was:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1211152/67662268-57b3f200-f963-11e9-8672-7551ff2311fd.png">
