### ISSUE TITLE
Combine random/interest dataset plans

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#83]
There are currently two test plans that cover transferring datasets: [interest](https://github.com/ipfs/testground/tree/master/plans/data-transfer-datasets-interest) and [random](https://github.com/ipfs/testground/tree/master/plans/data-transfer-datasets-random). However, the tests will be identical. The only difference is the input data.

We could simplify them by:

1. Combining them.
2. Allowing the user to specify the data source:
  * Generated files as specified in https://github.com/ipfs/testground/issues/80
  * An IPFS path.

**Comment by daviddias** [comment]
The main different (that is not yet apparent) is that the _random datasets_ will have a single access pattern while the _datasets of interest_ will have access patterns that mimic normal user interaction, hence the separation

**Comment by daviddias** [comment]
We can actually do this by separating the "special access patterns with no special access patterns" by test case. Taking in this suggestion with https://github.com/ipfs/testground/pull/242
