### ISSUE TITLE
Use Ansible to automate cluster setup

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#84]
This is close to becoming a PR ... I've been experimenting and prototyping in the [aws-ansible](https://github.com/ipfs/testground/tree/aws-ansible) branch to learn a bit of Ansible so I can have reproducible cluster setups (a serious pain point for me so far).

I've got playbooks working for:

* [Dynamic Inventory](https://github.com/ipfs/testground/blob/aws-ansible/tools/aws-setup/list-hosts.sh) - retrieve the list of machines from the AWS EC2 API that are tagged with the same 'TG' tag as the current host
* [Connectivity Test](https://github.com/ipfs/testground/blob/aws-ansible/tools/aws-setup/ping-all.sh) - ping all the hosts in the inventory
* [Redis](https://github.com/ipfs/testground/blob/aws-ansible/tools/aws-setup/setup-redis.yml) - setup the redis.conf config file on the first machine and start the server
* [Filebeat](https://github.com/ipfs/testground/blob/aws-ansible/tools/aws-setup/setup-filebeat.yml) - setup the filebeat.yml from a template populated from an ansible config stored in an S3 bucket
* [Networking](https://github.com/ipfs/testground/blob/aws-ansible/tools/aws-setup/setup-networking.yml) - setup Docker networking on each machine with non-overlapping subnets and GRE tunnels (currently setup for 2 machines, will generalize it for 2+ soon)

I'm planning to take these individual scripts and put them into a directory as [Ansible "roles"](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html) so they can be run all together.

**Comment by daviddias** [comment]
Related PR: #111

**Comment by daviddias** [comment]
@jimpick does #111 achieve all of the above? Shall we close this issue in favor of using #111 for tracking the remaining of the work?

**Comment by jimpick** [comment]
Yep, I'll close this one as it's all in the PR.

**Comment by jimpick** [comment]
For posterity ... I almost lost the git ref after the branch was deleted:

This the Ansible GRE tunnel automation from the `aws-ansible` branch:

https://github.com/ipfs/testground/blob/3f3b8ed8e66bfc1ea64318b0e36a2ffc2403140c/tools/aws-setup/setup-gre-networking.yml

Also saved at:

https://github.com/jimpick/testground/blob/ansible-gre-tunnels/tools/aws-setup/setup-gre-networking.yml
