### ISSUE TITLE
Impl Plan - Nodes Connectivity (Transports, Hole Punching, Relay)

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#96]
Plan Description: https://github.com/ipfs/testground/blob/master/plans/nodes-connectivity

**Comment by jimpick** [comment]
I did some experimentation, and I found a good tutorial for how to use Linux namespaces ... I was able to set up a NAT from inside a privileged Docker container:

https://blogs.igalia.com/dpino/2016/04/10/network-namespaces/

Potentially, this is something that could be handled by the sidecar daemon.

**Comment by jimpick** [comment]
The test plan will need some work to fully flesh out ... there are a lot of blanks in the README right now.

Over the weekend, I thought through some ideas ... my current vision is that this test plan will serve the role of a "connectivity obstacle course" - we can use it to model connectivity challenges, and deploy various solutions into it (eg. relay, preload nodes, delegated routing, websockets, hole-punching, WebRTC, distributed signalling, alternate transports, etc.)

Many of the individual test cases could be quite small - eg. a single non-NATed node trying to talk to a NATed node via relay. A lot of the outcomes are boolean - either there is connectivity or there isn't.

More complicated scenarios might test connection upgrading, eg. starting with relay, and then moving to a hole-punched connection.

For things like hole punching, there are different types of NATs to model.

In the beginning, there probably isn't a lot of value in trying to simulate scenarios with thousands of nodes. It might be worth doing to try to model congestion/saturation issues with shared infrastructure (eg. relays, preload nodes).

I can imagine a progression in complexity for the test cases. The very simplest test case is a libp2p ping between two nodes that are connected via TCP. A further step would be to introduce a NAT on one side, and then introduce a relay. Two NATs shouldn't be much different. Hole punching could then be tested with one NAT or two NATs. It starts to get really complicated once we try to bridge connectivity into web browsers and try to use WebRTC.

**Comment by daviddias** [comment]
> The following notes come from a 1:1 discussion between @jimpick & @daviddias, and @jimpick's request to help unpack what this Test Plan oughts to be.

The goal of Test Plan 4 is to create a Plan that puts libp2p to test when it comes to a multitude of connectivity scenarios. This translates to a Test Plan that will require a high degree of creativity in order to incorporate a series of real world scenarios into the Testing Pipeline. In Summary:

- What this Test Plan **is about**:
    - Simulating real world conditions
    - Test the multitude of connectivity scenarios possible using libp2p (TCP, uTP, QUIC, Relay, WebRTC, WebRTC with Turn, and so on)
- What this Test Plan **is not about**:
    - Spawning hundreds to thousands of nodes. In fact, this test plan should not even require anything specific from AWS (or other cloud) infrastructure. All tests should run relatively fast on a developer machine and these should be reproducible independent of the developer machine main environment.
    - Relying solely on sidecar to set up network configurations. This test plan will have to import and leverage multiple tools (OpenVSwitch, Linux Namespaces / Mininet, etc) that exist to simulate real world scenarios, so that it has a large breath of coverage Using sidecar to run simulations.

The Plan Spec that currently exists on https://github.com/ipfs/testground/tree/master/plans/nodes-connectivity is purely a draft and should not be taken for granted as something directly implementable. The Spec will require iteration first.

Ideally, what we want to have is a grid in which the columns are the Network scenario and the rows are the possible configurations.

Example (for interpretation):
| PeerA   | PeerB | Scenario 1 | Scenario 2 | 
| ------- | -------- | ------------ | -- |
| TCP+uTP | TCP+QUIC | ✅         | ❌ |
| TCP+Relay | WebRTC+Relay | ✅         | ✅ |

In addition, it is important to have a _stress_ parameter, something that a developer can tune to increase the work done by the transport set up. This is important because we already learned the hard way that things break under stress:
- spdystream seemed fine until we tried to transfer multiple MB files
- circuit-relay seemed complete but it was not stable

The stress can come in different ways, from the time the connection stays open, the number of muxed streams that are open on that connection, the amount of data that gets transferred for the test, etc.


------ 

As a first milestone for @jimpick, the goal is to:

**Milestone 1**

Implement the Circuit Relay Testing, leveraging sidecar to create the following scenarios:
- Same LAN
- Different Subnets that are not routable to each other

You can draw inspiration from https://github.com/ipfs/interop/blob/master/test/circuit/all.js for the Test Cases

**Milestone 2** should be about coming up with the grid referenced above and start hitting each test case for each cell in the grid.

**Comment by jimpick** [comment]
I've been working on #287 as an exploration / template for basic connectivity tests. I'm going to sketch out a basic progression of simple tests I'd like to implement so it becomes possible to identify subtasks.

**Comment by daviddias** [comment]
@jimpick it is correct to unassign you as you moved to focus in another project, correct?

**Comment by jimpick** [comment]
Correct ... I had done some background work on it and wanted to have some more conversation about it, but I'm now on a different team.

**Comment by raulk** [comment]
Thanks for all the work and thoughts here!

We are focusing our test plan building efforts on the DHT test plan, Bitswap, Gossipsub, go-lotus. Simulating real-world conditions is not trivial and this will require an important focused intellectual investment. It is not relevant for now; our current critical tests can be performed by advertising addresses we are not listening on. Closing for now, will revisit later.
