### ISSUE TITLE
Impl Plan - The go-libp2p DHT behaves correctly (essential plan to unblock go-ipfs 0.5.0 testing)

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#97]
~~Plan Description: https://github.com/ipfs/testground/blob/master/plans/providing-content~~

### Plan Description: https://github.com/ipfs/testground/tree/master/plans/dht

**Comment by daviddias** [comment]
This is being superseeded by https://github.com/ipfs/testground/tree/master/plans/dht

**Comment by daviddias** [comment]
Following @raulk's prompt for a review of https://github.com/libp2p/go-libp2p-kad-dht/issues/345 and a expansion of the DHT Test Plan scope based on the multiple changes happening in the DHT, I am now review what those are and figuring out the best way to test. I've a couple of questions though, which I'm asking here.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1211152/70638213-c1990a00-1c38-11ea-928a-797a12e56a16.png">

Waiting on https://github.com/libp2p/go-libp2p-kad-dht/issues/345#issuecomment-564608164 to understand what backtracing is.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1211152/70638257-d2e21680-1c38-11ea-8c7a-a4fbc687c0b0.png">

Add tests to prove that:

- [ ] Records are replicating in more nodes as more nodes request the content
- [ ] Records are replicated less once the content becomes less requested

<img width="640" alt="image" src="https://user-images.githubusercontent.com/1211152/70638313-f4db9900-1c38-11ea-9e2d-239ced2c9f45.png">

Wait for a follow up on https://github.com/libp2p/go-libp2p-kad-dht/issues/345#issuecomment-564609512 to understand what is the current behavior and what is the behavior that we want to deploy

<img width="659" alt="image" src="https://user-images.githubusercontent.com/1211152/70638415-23597400-1c39-11ea-9e1b-fb98a2d41d22.png">

Add tests to prove that:

- [ ] The peers switch to client or full node depending on their network conditions

<img width="639" alt="image" src="https://user-images.githubusercontent.com/1211152/70638467-39ffcb00-1c39-11ea-8ef5-0831ce77ecb6.png">

Add tests to prove that

- [  ] A peer recovers their routing table even after a shutdown and reboot

<img width="634" alt="image" src="https://user-images.githubusercontent.com/1211152/70638567-67e50f80-1c39-11ea-96ed-0c2d00c8b3dc.png">

Seeking to understand if any progress on this has been done.

PS: @raulk thank you for pointing that issue to me. Super useful to comprehend how I can augment the tests!.

**Comment by raulk** [comment]
This issue is rotten and doesn't capture the status quo of the DHT test plan. Will be closing down to avoid misunderstandings.
